// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: metadata/metadata.proto

package metadata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Network int32

const (
	// Avoid a default value since a default and a bug are not distinguishable
	Network_NETWORK_DO_NOT_USE Network = 0
	Network_MAINNET            Network = 1
	Network_TESTNET            Network = 2
	Network_DEVNET             Network = 3
)

// Enum value maps for Network.
var (
	Network_name = map[int32]string{
		0: "NETWORK_DO_NOT_USE",
		1: "MAINNET",
		2: "TESTNET",
		3: "DEVNET",
	}
	Network_value = map[string]int32{
		"NETWORK_DO_NOT_USE": 0,
		"MAINNET":            1,
		"TESTNET":            2,
		"DEVNET":             3,
	}
)

func (x Network) Enum() *Network {
	p := new(Network)
	*p = x
	return p
}

func (x Network) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Network) Descriptor() protoreflect.EnumDescriptor {
	return file_metadata_metadata_proto_enumTypes[0].Descriptor()
}

func (Network) Type() protoreflect.EnumType {
	return &file_metadata_metadata_proto_enumTypes[0]
}

func (x Network) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Network.Descriptor instead.
func (Network) EnumDescriptor() ([]byte, []int) {
	return file_metadata_metadata_proto_rawDescGZIP(), []int{0}
}

type MetaData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mainnet, testnet, devnet, can also be some virtually defined network (extra devnet for testing, extra mainnnet node for scanning historical blocks, etc)
	Network          Network                `protobuf:"varint,1,opt,name=Network,proto3,enum=metadata.Network" json:"Network,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"` // Internal to listener
	UpdatedByAccount *string                `protobuf:"bytes,4,opt,name=UpdatedByAccount,proto3,oneof" json:"UpdatedByAccount,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MetaData) Reset() {
	*x = MetaData{}
	mi := &file_metadata_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaData) ProtoMessage() {}

func (x *MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaData.ProtoReflect.Descriptor instead.
func (*MetaData) Descriptor() ([]byte, []int) {
	return file_metadata_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *MetaData) GetNetwork() Network {
	if x != nil {
		return x.Network
	}
	return Network_NETWORK_DO_NOT_USE
}

func (x *MetaData) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *MetaData) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MetaData) GetUpdatedByAccount() string {
	if x != nil && x.UpdatedByAccount != nil {
		return *x.UpdatedByAccount
	}
	return ""
}

var File_metadata_metadata_proto protoreflect.FileDescriptor

const file_metadata_metadata_proto_rawDesc = "" +
	"\n" +
	"\x17metadata/metadata.proto\x12\bmetadata\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf1\x01\n" +
	"\bMetaData\x12+\n" +
	"\aNetwork\x18\x01 \x01(\x0e2\x11.metadata.NetworkR\aNetwork\x128\n" +
	"\tUpdatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x128\n" +
	"\tCreatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x12/\n" +
	"\x10UpdatedByAccount\x18\x04 \x01(\tH\x00R\x10UpdatedByAccount\x88\x01\x01B\x13\n" +
	"\x11_UpdatedByAccount*G\n" +
	"\aNetwork\x12\x16\n" +
	"\x12NETWORK_DO_NOT_USE\x10\x00\x12\v\n" +
	"\aMAINNET\x10\x01\x12\v\n" +
	"\aTESTNET\x10\x02\x12\n" +
	"\n" +
	"\x06DEVNET\x10\x03B@Z>github.com/sologenic/com-fs-utils-lib/models/metadata;metadatab\x06proto3"

var (
	file_metadata_metadata_proto_rawDescOnce sync.Once
	file_metadata_metadata_proto_rawDescData []byte
)

func file_metadata_metadata_proto_rawDescGZIP() []byte {
	file_metadata_metadata_proto_rawDescOnce.Do(func() {
		file_metadata_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metadata_metadata_proto_rawDesc), len(file_metadata_metadata_proto_rawDesc)))
	})
	return file_metadata_metadata_proto_rawDescData
}

var file_metadata_metadata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_metadata_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_metadata_metadata_proto_goTypes = []any{
	(Network)(0),                  // 0: metadata.Network
	(*MetaData)(nil),              // 1: metadata.MetaData
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_metadata_metadata_proto_depIdxs = []int32{
	0, // 0: metadata.MetaData.Network:type_name -> metadata.Network
	2, // 1: metadata.MetaData.UpdatedAt:type_name -> google.protobuf.Timestamp
	2, // 2: metadata.MetaData.CreatedAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_metadata_metadata_proto_init() }
func file_metadata_metadata_proto_init() {
	if File_metadata_metadata_proto != nil {
		return
	}
	file_metadata_metadata_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metadata_metadata_proto_rawDesc), len(file_metadata_metadata_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metadata_metadata_proto_goTypes,
		DependencyIndexes: file_metadata_metadata_proto_depIdxs,
		EnumInfos:         file_metadata_metadata_proto_enumTypes,
		MessageInfos:      file_metadata_metadata_proto_msgTypes,
	}.Build()
	File_metadata_metadata_proto = out.File
	file_metadata_metadata_proto_goTypes = nil
	file_metadata_metadata_proto_depIdxs = nil
}
