// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: role/role.proto

package role

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_NOT_USED_ROLE                  Role = 0
	Role_NORMAL_USER                    Role = 1
	Role_VIEWER                         Role = 2
	Role_BROKER_ASSET_ADMINISTRATOR     Role = 3
	Role_ORGANIZATION_ADMINISTRATOR     Role = 4
	Role_BROKER_ASSET_VIEWER            Role = 5
	Role_SOLOGENIC_ADMINISTRATOR        Role = 6 // Highest level of administrator. Can only create new Organizations and assign an initial administrator in there
	Role_TX_ADMINISTRATOR               Role = 6 // Alias for SOLOGENIC_ADMINISTRATOR
	Role_KYC_ADMINISTRATOR              Role = 7
	Role_TX_ACCOUNT_MANAGER             Role = 8  // Manages partners and partner assignments
	Role_TX_USER_MANAGER                Role = 9  // Manages user/referral aspects
	Role_PARTNER_BROKER_ADMIN           Role = 10 // Can manage partner users for broker partner, and view partner dashboard
	Role_PARTNER_BROKER_ACCOUNT_MANAGER Role = 11 // Day-to-day broker ops, create orgs via wizard, approvals if allowed
	// Partner scope hierarchy for sales channel
	Role_PARTNER_SALES_ADMIN           Role = 12
	Role_PARTNER_SALES_ACCOUNT_MANAGER Role = 13
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "NOT_USED_ROLE",
		1: "NORMAL_USER",
		2: "VIEWER",
		3: "BROKER_ASSET_ADMINISTRATOR",
		4: "ORGANIZATION_ADMINISTRATOR",
		5: "BROKER_ASSET_VIEWER",
		6: "SOLOGENIC_ADMINISTRATOR",
		// Duplicate value: 6: "TX_ADMINISTRATOR",
		7:  "KYC_ADMINISTRATOR",
		8:  "TX_ACCOUNT_MANAGER",
		9:  "TX_USER_MANAGER",
		10: "PARTNER_BROKER_ADMIN",
		11: "PARTNER_BROKER_ACCOUNT_MANAGER",
		12: "PARTNER_SALES_ADMIN",
		13: "PARTNER_SALES_ACCOUNT_MANAGER",
	}
	Role_value = map[string]int32{
		"NOT_USED_ROLE":                  0,
		"NORMAL_USER":                    1,
		"VIEWER":                         2,
		"BROKER_ASSET_ADMINISTRATOR":     3,
		"ORGANIZATION_ADMINISTRATOR":     4,
		"BROKER_ASSET_VIEWER":            5,
		"SOLOGENIC_ADMINISTRATOR":        6,
		"TX_ADMINISTRATOR":               6,
		"KYC_ADMINISTRATOR":              7,
		"TX_ACCOUNT_MANAGER":             8,
		"TX_USER_MANAGER":                9,
		"PARTNER_BROKER_ADMIN":           10,
		"PARTNER_BROKER_ACCOUNT_MANAGER": 11,
		"PARTNER_SALES_ADMIN":            12,
		"PARTNER_SALES_ACCOUNT_MANAGER":  13,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_role_role_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_role_role_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_role_role_proto_rawDescGZIP(), []int{0}
}

var File_role_role_proto protoreflect.FileDescriptor

const file_role_role_proto_rawDesc = "" +
	"\n" +
	"\x0frole/role.proto\x12\x04role*\x84\x03\n" +
	"\x04Role\x12\x11\n" +
	"\rNOT_USED_ROLE\x10\x00\x12\x0f\n" +
	"\vNORMAL_USER\x10\x01\x12\n" +
	"\n" +
	"\x06VIEWER\x10\x02\x12\x1e\n" +
	"\x1aBROKER_ASSET_ADMINISTRATOR\x10\x03\x12\x1e\n" +
	"\x1aORGANIZATION_ADMINISTRATOR\x10\x04\x12\x17\n" +
	"\x13BROKER_ASSET_VIEWER\x10\x05\x12\x1b\n" +
	"\x17SOLOGENIC_ADMINISTRATOR\x10\x06\x12\x14\n" +
	"\x10TX_ADMINISTRATOR\x10\x06\x12\x15\n" +
	"\x11KYC_ADMINISTRATOR\x10\a\x12\x16\n" +
	"\x12TX_ACCOUNT_MANAGER\x10\b\x12\x13\n" +
	"\x0fTX_USER_MANAGER\x10\t\x12\x18\n" +
	"\x14PARTNER_BROKER_ADMIN\x10\n" +
	"\x12\"\n" +
	"\x1ePARTNER_BROKER_ACCOUNT_MANAGER\x10\v\x12\x17\n" +
	"\x13PARTNER_SALES_ADMIN\x10\f\x12!\n" +
	"\x1dPARTNER_SALES_ACCOUNT_MANAGER\x10\r\x1a\x02\x10\x01B8Z6github.com/sologenic/com-fs-utils-lib/models/role;roleb\x06proto3"

var (
	file_role_role_proto_rawDescOnce sync.Once
	file_role_role_proto_rawDescData []byte
)

func file_role_role_proto_rawDescGZIP() []byte {
	file_role_role_proto_rawDescOnce.Do(func() {
		file_role_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_role_role_proto_rawDesc), len(file_role_role_proto_rawDesc)))
	})
	return file_role_role_proto_rawDescData
}

var file_role_role_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_role_role_proto_goTypes = []any{
	(Role)(0), // 0: role.Role
}
var file_role_role_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_role_role_proto_init() }
func file_role_role_proto_init() {
	if File_role_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_role_proto_rawDesc), len(file_role_role_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_role_role_proto_goTypes,
		DependencyIndexes: file_role_role_proto_depIdxs,
		EnumInfos:         file_role_role_proto_enumTypes,
	}.Build()
	File_role_role_proto = out.File
	file_role_role_proto_goTypes = nil
	file_role_role_proto_depIdxs = nil
}
