// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: denom/denom.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";

export const protobufPackage = "denom";

export interface TokenPair {
  Maker: Denom | undefined;
  Taker: Denom | undefined;
}

export interface Denom {
  Currency: string;
  Issuer: string;
  Precision?: number | undefined;
  IsIBC: boolean;
}

function createBaseTokenPair(): TokenPair {
  return { Maker: undefined, Taker: undefined };
}

export const TokenPair = {
  encode(message: TokenPair, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Maker !== undefined) {
      Denom.encode(message.Maker, writer.uint32(10).fork()).ldelim();
    }
    if (message.Taker !== undefined) {
      Denom.encode(message.Taker, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TokenPair {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTokenPair();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Maker = Denom.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Taker = Denom.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TokenPair {
    return {
      Maker: isSet(object.Maker) ? Denom.fromJSON(object.Maker) : undefined,
      Taker: isSet(object.Taker) ? Denom.fromJSON(object.Taker) : undefined,
    };
  },

  toJSON(message: TokenPair): unknown {
    const obj: any = {};
    if (message.Maker !== undefined) {
      obj.Maker = Denom.toJSON(message.Maker);
    }
    if (message.Taker !== undefined) {
      obj.Taker = Denom.toJSON(message.Taker);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TokenPair>, I>>(base?: I): TokenPair {
    return TokenPair.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TokenPair>, I>>(object: I): TokenPair {
    const message = createBaseTokenPair();
    message.Maker = (object.Maker !== undefined && object.Maker !== null) ? Denom.fromPartial(object.Maker) : undefined;
    message.Taker = (object.Taker !== undefined && object.Taker !== null) ? Denom.fromPartial(object.Taker) : undefined;
    return message;
  },
};

function createBaseDenom(): Denom {
  return { Currency: "", Issuer: "", Precision: undefined, IsIBC: false };
}

export const Denom = {
  encode(message: Denom, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Currency !== "") {
      writer.uint32(10).string(message.Currency);
    }
    if (message.Issuer !== "") {
      writer.uint32(18).string(message.Issuer);
    }
    if (message.Precision !== undefined) {
      writer.uint32(24).int32(message.Precision);
    }
    if (message.IsIBC !== false) {
      writer.uint32(32).bool(message.IsIBC);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Denom {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDenom();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Currency = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Issuer = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.Precision = reader.int32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.IsIBC = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Denom {
    return {
      Currency: isSet(object.Currency) ? globalThis.String(object.Currency) : "",
      Issuer: isSet(object.Issuer) ? globalThis.String(object.Issuer) : "",
      Precision: isSet(object.Precision) ? globalThis.Number(object.Precision) : undefined,
      IsIBC: isSet(object.IsIBC) ? globalThis.Boolean(object.IsIBC) : false,
    };
  },

  toJSON(message: Denom): unknown {
    const obj: any = {};
    if (message.Currency !== "") {
      obj.Currency = message.Currency;
    }
    if (message.Issuer !== "") {
      obj.Issuer = message.Issuer;
    }
    if (message.Precision !== undefined) {
      obj.Precision = Math.round(message.Precision);
    }
    if (message.IsIBC !== false) {
      obj.IsIBC = message.IsIBC;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Denom>, I>>(base?: I): Denom {
    return Denom.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Denom>, I>>(object: I): Denom {
    const message = createBaseDenom();
    message.Currency = object.Currency ?? "";
    message.Issuer = object.Issuer ?? "";
    message.Precision = object.Precision ?? undefined;
    message.IsIBC = object.IsIBC ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
