// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: denom/denom.proto

package denom

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Maker         *Denom                 `protobuf:"bytes,1,opt,name=Maker,proto3" json:"Maker,omitempty"`
	Taker         *Denom                 `protobuf:"bytes,2,opt,name=Taker,proto3" json:"Taker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenPair) Reset() {
	*x = TokenPair{}
	mi := &file_denom_denom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPair) ProtoMessage() {}

func (x *TokenPair) ProtoReflect() protoreflect.Message {
	mi := &file_denom_denom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPair.ProtoReflect.Descriptor instead.
func (*TokenPair) Descriptor() ([]byte, []int) {
	return file_denom_denom_proto_rawDescGZIP(), []int{0}
}

func (x *TokenPair) GetMaker() *Denom {
	if x != nil {
		return x.Maker
	}
	return nil
}

func (x *TokenPair) GetTaker() *Denom {
	if x != nil {
		return x.Taker
	}
	return nil
}

type Denom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=Currency,proto3" json:"Currency,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=Issuer,proto3" json:"Issuer,omitempty"`
	Precision     *int32                 `protobuf:"varint,3,opt,name=Precision,proto3,oneof" json:"Precision,omitempty"`
	IsIBC         bool                   `protobuf:"varint,4,opt,name=IsIBC,proto3" json:"IsIBC,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Denom) Reset() {
	*x = Denom{}
	mi := &file_denom_denom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Denom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Denom) ProtoMessage() {}

func (x *Denom) ProtoReflect() protoreflect.Message {
	mi := &file_denom_denom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Denom.ProtoReflect.Descriptor instead.
func (*Denom) Descriptor() ([]byte, []int) {
	return file_denom_denom_proto_rawDescGZIP(), []int{1}
}

func (x *Denom) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Denom) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Denom) GetPrecision() int32 {
	if x != nil && x.Precision != nil {
		return *x.Precision
	}
	return 0
}

func (x *Denom) GetIsIBC() bool {
	if x != nil {
		return x.IsIBC
	}
	return false
}

var File_denom_denom_proto protoreflect.FileDescriptor

const file_denom_denom_proto_rawDesc = "" +
	"\n" +
	"\x11denom/denom.proto\x12\x05denom\"S\n" +
	"\tTokenPair\x12\"\n" +
	"\x05Maker\x18\x01 \x01(\v2\f.denom.DenomR\x05Maker\x12\"\n" +
	"\x05Taker\x18\x02 \x01(\v2\f.denom.DenomR\x05Taker\"\x82\x01\n" +
	"\x05Denom\x12\x1a\n" +
	"\bCurrency\x18\x01 \x01(\tR\bCurrency\x12\x16\n" +
	"\x06Issuer\x18\x02 \x01(\tR\x06Issuer\x12!\n" +
	"\tPrecision\x18\x03 \x01(\x05H\x00R\tPrecision\x88\x01\x01\x12\x14\n" +
	"\x05IsIBC\x18\x04 \x01(\bR\x05IsIBCB\f\n" +
	"\n" +
	"_PrecisionB:Z8github.com/sologenic/com-fs-utils-lib/models/denom;denomb\x06proto3"

var (
	file_denom_denom_proto_rawDescOnce sync.Once
	file_denom_denom_proto_rawDescData []byte
)

func file_denom_denom_proto_rawDescGZIP() []byte {
	file_denom_denom_proto_rawDescOnce.Do(func() {
		file_denom_denom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_denom_denom_proto_rawDesc), len(file_denom_denom_proto_rawDesc)))
	})
	return file_denom_denom_proto_rawDescData
}

var file_denom_denom_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_denom_denom_proto_goTypes = []any{
	(*TokenPair)(nil), // 0: denom.TokenPair
	(*Denom)(nil),     // 1: denom.Denom
}
var file_denom_denom_proto_depIdxs = []int32{
	1, // 0: denom.TokenPair.Maker:type_name -> denom.Denom
	1, // 1: denom.TokenPair.Taker:type_name -> denom.Denom
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_denom_denom_proto_init() }
func file_denom_denom_proto_init() {
	if File_denom_denom_proto != nil {
		return
	}
	file_denom_denom_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_denom_denom_proto_rawDesc), len(file_denom_denom_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_denom_denom_proto_goTypes,
		DependencyIndexes: file_denom_denom_proto_depIdxs,
		MessageInfos:      file_denom_denom_proto_msgTypes,
	}.Build()
	File_denom_denom_proto = out.File
	file_denom_denom_proto_goTypes = nil
	file_denom_denom_proto_depIdxs = nil
}
