// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v6.32.0
// source: denom/denom.proto

package denom

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Maker *Denom `protobuf:"bytes,1,opt,name=Maker,proto3" json:"Maker,omitempty"`
	Taker *Denom `protobuf:"bytes,2,opt,name=Taker,proto3" json:"Taker,omitempty"`
}

func (x *TokenPair) Reset() {
	*x = TokenPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_denom_denom_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPair) ProtoMessage() {}

func (x *TokenPair) ProtoReflect() protoreflect.Message {
	mi := &file_denom_denom_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPair.ProtoReflect.Descriptor instead.
func (*TokenPair) Descriptor() ([]byte, []int) {
	return file_denom_denom_proto_rawDescGZIP(), []int{0}
}

func (x *TokenPair) GetMaker() *Denom {
	if x != nil {
		return x.Maker
	}
	return nil
}

func (x *TokenPair) GetTaker() *Denom {
	if x != nil {
		return x.Taker
	}
	return nil
}

type Denom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Currency  string `protobuf:"bytes,1,opt,name=Currency,proto3" json:"Currency,omitempty"`
	Issuer    string `protobuf:"bytes,2,opt,name=Issuer,proto3" json:"Issuer,omitempty"`
	Precision *int32 `protobuf:"varint,3,opt,name=Precision,proto3,oneof" json:"Precision,omitempty"`
	IsIBC     bool   `protobuf:"varint,4,opt,name=IsIBC,proto3" json:"IsIBC,omitempty"`
}

func (x *Denom) Reset() {
	*x = Denom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_denom_denom_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Denom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Denom) ProtoMessage() {}

func (x *Denom) ProtoReflect() protoreflect.Message {
	mi := &file_denom_denom_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Denom.ProtoReflect.Descriptor instead.
func (*Denom) Descriptor() ([]byte, []int) {
	return file_denom_denom_proto_rawDescGZIP(), []int{1}
}

func (x *Denom) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Denom) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Denom) GetPrecision() int32 {
	if x != nil && x.Precision != nil {
		return *x.Precision
	}
	return 0
}

func (x *Denom) GetIsIBC() bool {
	if x != nil {
		return x.IsIBC
	}
	return false
}

var File_denom_denom_proto protoreflect.FileDescriptor

var file_denom_denom_proto_rawDesc = []byte{
	0x0a, 0x11, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x22, 0x53, 0x0a, 0x09, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x50, 0x61, 0x69, 0x72, 0x12, 0x22, 0x0a, 0x05, 0x4d, 0x61, 0x6b, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x2e, 0x44,
	0x65, 0x6e, 0x6f, 0x6d, 0x52, 0x05, 0x4d, 0x61, 0x6b, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x05, 0x54,
	0x61, 0x6b, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x65, 0x6e,
	0x6f, 0x6d, 0x2e, 0x44, 0x65, 0x6e, 0x6f, 0x6d, 0x52, 0x05, 0x54, 0x61, 0x6b, 0x65, 0x72, 0x22,
	0x82, 0x01, 0x0a, 0x05, 0x44, 0x65, 0x6e, 0x6f, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x73, 0x75, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x49, 0x73, 0x73, 0x75, 0x65, 0x72, 0x12, 0x21, 0x0a,
	0x09, 0x50, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x00, 0x52, 0x09, 0x50, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01,
	0x12, 0x14, 0x0a, 0x05, 0x49, 0x73, 0x49, 0x42, 0x43, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x49, 0x73, 0x49, 0x42, 0x43, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x50, 0x72, 0x65, 0x63, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x6c, 0x6f, 0x67, 0x65, 0x6e, 0x69, 0x63, 0x2f, 0x63, 0x6f, 0x6d,
	0x2d, 0x66, 0x73, 0x2d, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2d, 0x6c, 0x69, 0x62, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2f, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x3b, 0x64, 0x65, 0x6e, 0x6f, 0x6d,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_denom_denom_proto_rawDescOnce sync.Once
	file_denom_denom_proto_rawDescData = file_denom_denom_proto_rawDesc
)

func file_denom_denom_proto_rawDescGZIP() []byte {
	file_denom_denom_proto_rawDescOnce.Do(func() {
		file_denom_denom_proto_rawDescData = protoimpl.X.CompressGZIP(file_denom_denom_proto_rawDescData)
	})
	return file_denom_denom_proto_rawDescData
}

var file_denom_denom_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_denom_denom_proto_goTypes = []interface{}{
	(*TokenPair)(nil), // 0: denom.TokenPair
	(*Denom)(nil),     // 1: denom.Denom
}
var file_denom_denom_proto_depIdxs = []int32{
	1, // 0: denom.TokenPair.Maker:type_name -> denom.Denom
	1, // 1: denom.TokenPair.Taker:type_name -> denom.Denom
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_denom_denom_proto_init() }
func file_denom_denom_proto_init() {
	if File_denom_denom_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_denom_denom_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_denom_denom_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Denom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_denom_denom_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_denom_denom_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_denom_denom_proto_goTypes,
		DependencyIndexes: file_denom_denom_proto_depIdxs,
		MessageInfos:      file_denom_denom_proto_msgTypes,
	}.Build()
	File_denom_denom_proto = out.File
	file_denom_denom_proto_rawDesc = nil
	file_denom_denom_proto_goTypes = nil
	file_denom_denom_proto_depIdxs = nil
}
