// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: language/language.proto

package language

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lang int32

const (
	Lang_LANG_NOT_USED Lang = 0
	Lang_ENGLISH       Lang = 1
	Lang_SPANISH       Lang = 2
	Lang_KOREAN        Lang = 3
)

// Enum value maps for Lang.
var (
	Lang_name = map[int32]string{
		0: "LANG_NOT_USED",
		1: "ENGLISH",
		2: "SPANISH",
		3: "KOREAN",
	}
	Lang_value = map[string]int32{
		"LANG_NOT_USED": 0,
		"ENGLISH":       1,
		"SPANISH":       2,
		"KOREAN":        3,
	}
)

func (x Lang) Enum() *Lang {
	p := new(Lang)
	*p = x
	return p
}

func (x Lang) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Lang) Descriptor() protoreflect.EnumDescriptor {
	return file_language_language_proto_enumTypes[0].Descriptor()
}

func (Lang) Type() protoreflect.EnumType {
	return &file_language_language_proto_enumTypes[0]
}

func (x Lang) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Lang.Descriptor instead.
func (Lang) EnumDescriptor() ([]byte, []int) {
	return file_language_language_proto_rawDescGZIP(), []int{0}
}

type Language struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Language       Lang                   `protobuf:"varint,1,opt,name=Language,proto3,enum=language.Lang" json:"Language,omitempty"`
	UserConfigured bool                   `protobuf:"varint,2,opt,name=UserConfigured,proto3" json:"UserConfigured,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Language) Reset() {
	*x = Language{}
	mi := &file_language_language_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Language) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Language) ProtoMessage() {}

func (x *Language) ProtoReflect() protoreflect.Message {
	mi := &file_language_language_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Language.ProtoReflect.Descriptor instead.
func (*Language) Descriptor() ([]byte, []int) {
	return file_language_language_proto_rawDescGZIP(), []int{0}
}

func (x *Language) GetLanguage() Lang {
	if x != nil {
		return x.Language
	}
	return Lang_LANG_NOT_USED
}

func (x *Language) GetUserConfigured() bool {
	if x != nil {
		return x.UserConfigured
	}
	return false
}

var File_language_language_proto protoreflect.FileDescriptor

const file_language_language_proto_rawDesc = "" +
	"\n" +
	"\x17language/language.proto\x12\blanguage\"^\n" +
	"\bLanguage\x12*\n" +
	"\bLanguage\x18\x01 \x01(\x0e2\x0e.language.LangR\bLanguage\x12&\n" +
	"\x0eUserConfigured\x18\x02 \x01(\bR\x0eUserConfigured*?\n" +
	"\x04Lang\x12\x11\n" +
	"\rLANG_NOT_USED\x10\x00\x12\v\n" +
	"\aENGLISH\x10\x01\x12\v\n" +
	"\aSPANISH\x10\x02\x12\n" +
	"\n" +
	"\x06KOREAN\x10\x03B@Z>github.com/sologenic/com-fs-utils-lib/models/language;languageb\x06proto3"

var (
	file_language_language_proto_rawDescOnce sync.Once
	file_language_language_proto_rawDescData []byte
)

func file_language_language_proto_rawDescGZIP() []byte {
	file_language_language_proto_rawDescOnce.Do(func() {
		file_language_language_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_language_language_proto_rawDesc), len(file_language_language_proto_rawDesc)))
	})
	return file_language_language_proto_rawDescData
}

var file_language_language_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_language_language_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_language_language_proto_goTypes = []any{
	(Lang)(0),        // 0: language.Lang
	(*Language)(nil), // 1: language.Language
}
var file_language_language_proto_depIdxs = []int32{
	0, // 0: language.Language.Language:type_name -> language.Lang
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_language_language_proto_init() }
func file_language_language_proto_init() {
	if File_language_language_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_language_language_proto_rawDesc), len(file_language_language_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_language_language_proto_goTypes,
		DependencyIndexes: file_language_language_proto_depIdxs,
		EnumInfos:         file_language_language_proto_enumTypes,
		MessageInfos:      file_language_language_proto_msgTypes,
	}.Build()
	File_language_language_proto = out.File
	file_language_language_proto_goTypes = nil
	file_language_language_proto_depIdxs = nil
}
