// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v6.32.0
// source: language/language.proto

package language

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lang int32

const (
	Lang_LANG_NOT_USED Lang = 0
	Lang_ENGLISH       Lang = 1
	Lang_SPANISH       Lang = 2
	Lang_KOREAN        Lang = 3
)

// Enum value maps for Lang.
var (
	Lang_name = map[int32]string{
		0: "LANG_NOT_USED",
		1: "ENGLISH",
		2: "SPANISH",
		3: "KOREAN",
	}
	Lang_value = map[string]int32{
		"LANG_NOT_USED": 0,
		"ENGLISH":       1,
		"SPANISH":       2,
		"KOREAN":        3,
	}
)

func (x Lang) Enum() *Lang {
	p := new(Lang)
	*p = x
	return p
}

func (x Lang) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Lang) Descriptor() protoreflect.EnumDescriptor {
	return file_language_language_proto_enumTypes[0].Descriptor()
}

func (Lang) Type() protoreflect.EnumType {
	return &file_language_language_proto_enumTypes[0]
}

func (x Lang) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Lang.Descriptor instead.
func (Lang) EnumDescriptor() ([]byte, []int) {
	return file_language_language_proto_rawDescGZIP(), []int{0}
}

type Language struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language       Lang `protobuf:"varint,1,opt,name=Language,proto3,enum=language.Lang" json:"Language,omitempty"`
	UserConfigured bool `protobuf:"varint,2,opt,name=UserConfigured,proto3" json:"UserConfigured,omitempty"`
}

func (x *Language) Reset() {
	*x = Language{}
	if protoimpl.UnsafeEnabled {
		mi := &file_language_language_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Language) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Language) ProtoMessage() {}

func (x *Language) ProtoReflect() protoreflect.Message {
	mi := &file_language_language_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Language.ProtoReflect.Descriptor instead.
func (*Language) Descriptor() ([]byte, []int) {
	return file_language_language_proto_rawDescGZIP(), []int{0}
}

func (x *Language) GetLanguage() Lang {
	if x != nil {
		return x.Language
	}
	return Lang_LANG_NOT_USED
}

func (x *Language) GetUserConfigured() bool {
	if x != nil {
		return x.UserConfigured
	}
	return false
}

var File_language_language_proto protoreflect.FileDescriptor

var file_language_language_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x2f, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x22, 0x5e, 0x0a, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12,
	0x2a, 0x0a, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0e, 0x2e, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x2e, 0x4c, 0x61, 0x6e,
	0x67, 0x52, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x55,
	0x73, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x65, 0x64, 0x2a, 0x3f, 0x0a, 0x04, 0x4c, 0x61, 0x6e, 0x67, 0x12, 0x11, 0x0a, 0x0d, 0x4c,
	0x41, 0x4e, 0x47, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x55, 0x53, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x45, 0x4e, 0x47, 0x4c, 0x49, 0x53, 0x48, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x50, 0x41, 0x4e, 0x49, 0x53, 0x48, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4b, 0x4f, 0x52, 0x45,
	0x41, 0x4e, 0x10, 0x03, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x6c, 0x6f, 0x67, 0x65, 0x6e, 0x69, 0x63, 0x2f, 0x63, 0x6f, 0x6d,
	0x2d, 0x66, 0x73, 0x2d, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2d, 0x6c, 0x69, 0x62, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2f, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x3b, 0x6c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_language_language_proto_rawDescOnce sync.Once
	file_language_language_proto_rawDescData = file_language_language_proto_rawDesc
)

func file_language_language_proto_rawDescGZIP() []byte {
	file_language_language_proto_rawDescOnce.Do(func() {
		file_language_language_proto_rawDescData = protoimpl.X.CompressGZIP(file_language_language_proto_rawDescData)
	})
	return file_language_language_proto_rawDescData
}

var file_language_language_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_language_language_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_language_language_proto_goTypes = []interface{}{
	(Lang)(0),        // 0: language.Lang
	(*Language)(nil), // 1: language.Language
}
var file_language_language_proto_depIdxs = []int32{
	0, // 0: language.Language.Language:type_name -> language.Lang
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_language_language_proto_init() }
func file_language_language_proto_init() {
	if File_language_language_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_language_language_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Language); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_language_language_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_language_language_proto_goTypes,
		DependencyIndexes: file_language_language_proto_depIdxs,
		EnumInfos:         file_language_language_proto_enumTypes,
		MessageInfos:      file_language_language_proto_msgTypes,
	}.Build()
	File_language_language_proto = out.File
	file_language_language_proto_rawDesc = nil
	file_language_language_proto_goTypes = nil
	file_language_language_proto_depIdxs = nil
}
