// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.32.0
// source: language/language.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";

export const protobufPackage = "language";

export enum Lang {
  LANG_NOT_USED = 0,
  ENGLISH = 1,
  SPANISH = 2,
  KOREAN = 3,
  UNRECOGNIZED = -1,
}

export function langFromJSON(object: any): Lang {
  switch (object) {
    case 0:
    case "LANG_NOT_USED":
      return Lang.LANG_NOT_USED;
    case 1:
    case "ENGLISH":
      return Lang.ENGLISH;
    case 2:
    case "SPANISH":
      return Lang.SPANISH;
    case 3:
    case "KOREAN":
      return Lang.KOREAN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Lang.UNRECOGNIZED;
  }
}

export function langToJSON(object: Lang): string {
  switch (object) {
    case Lang.LANG_NOT_USED:
      return "LANG_NOT_USED";
    case Lang.ENGLISH:
      return "ENGLISH";
    case Lang.SPANISH:
      return "SPANISH";
    case Lang.KOREAN:
      return "KOREAN";
    case Lang.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Language {
  Language: Lang;
  UserConfigured: boolean;
}

function createBaseLanguage(): Language {
  return { Language: 0, UserConfigured: false };
}

export const Language = {
  encode(message: Language, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Language !== 0) {
      writer.uint32(8).int32(message.Language);
    }
    if (message.UserConfigured !== false) {
      writer.uint32(16).bool(message.UserConfigured);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Language {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLanguage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.Language = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.UserConfigured = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Language {
    return {
      Language: isSet(object.Language) ? langFromJSON(object.Language) : 0,
      UserConfigured: isSet(object.UserConfigured) ? globalThis.Boolean(object.UserConfigured) : false,
    };
  },

  toJSON(message: Language): unknown {
    const obj: any = {};
    if (message.Language !== 0) {
      obj.Language = langToJSON(message.Language);
    }
    if (message.UserConfigured !== false) {
      obj.UserConfigured = message.UserConfigured;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Language>, I>>(base?: I): Language {
    return Language.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Language>, I>>(object: I): Language {
    const message = createBaseLanguage();
    message.Language = object.Language ?? 0;
    message.UserConfigured = object.UserConfigured ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
