// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.32.1
// source: audit/audit.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "audit";

export interface Audit {
  ChangedBy: string;
  ChangedAt: Date | undefined;
  Reason?: string | undefined;
}

function createBaseAudit(): Audit {
  return { ChangedBy: "", ChangedAt: undefined, Reason: undefined };
}

export const Audit = {
  encode(message: Audit, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.ChangedBy !== "") {
      writer.uint32(10).string(message.ChangedBy);
    }
    if (message.ChangedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.ChangedAt), writer.uint32(18).fork()).ldelim();
    }
    if (message.Reason !== undefined) {
      writer.uint32(26).string(message.Reason);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Audit {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAudit();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.ChangedBy = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.ChangedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.Reason = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Audit {
    return {
      ChangedBy: isSet(object.ChangedBy) ? globalThis.String(object.ChangedBy) : "",
      ChangedAt: isSet(object.ChangedAt) ? fromJsonTimestamp(object.ChangedAt) : undefined,
      Reason: isSet(object.Reason) ? globalThis.String(object.Reason) : undefined,
    };
  },

  toJSON(message: Audit): unknown {
    const obj: any = {};
    if (message.ChangedBy !== "") {
      obj.ChangedBy = message.ChangedBy;
    }
    if (message.ChangedAt !== undefined) {
      obj.ChangedAt = message.ChangedAt.toISOString();
    }
    if (message.Reason !== undefined) {
      obj.Reason = message.Reason;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Audit>, I>>(base?: I): Audit {
    return Audit.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Audit>, I>>(object: I): Audit {
    const message = createBaseAudit();
    message.ChangedBy = object.ChangedBy ?? "";
    message.ChangedAt = object.ChangedAt ?? undefined;
    message.Reason = object.Reason ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
