// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: audit/audit.proto

package audit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Audit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangedBy     string                 `protobuf:"bytes,1,opt,name=ChangedBy,proto3" json:"ChangedBy,omitempty"`
	ChangedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ChangedAt,proto3" json:"ChangedAt,omitempty"`
	Reason        *string                `protobuf:"bytes,3,opt,name=Reason,proto3,oneof" json:"Reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Audit) Reset() {
	*x = Audit{}
	mi := &file_audit_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Audit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audit) ProtoMessage() {}

func (x *Audit) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audit.ProtoReflect.Descriptor instead.
func (*Audit) Descriptor() ([]byte, []int) {
	return file_audit_audit_proto_rawDescGZIP(), []int{0}
}

func (x *Audit) GetChangedBy() string {
	if x != nil {
		return x.ChangedBy
	}
	return ""
}

func (x *Audit) GetChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangedAt
	}
	return nil
}

func (x *Audit) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

var File_audit_audit_proto protoreflect.FileDescriptor

const file_audit_audit_proto_rawDesc = "" +
	"\n" +
	"\x11audit/audit.proto\x12\x05audit\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x01\n" +
	"\x05Audit\x12\x1c\n" +
	"\tChangedBy\x18\x01 \x01(\tR\tChangedBy\x128\n" +
	"\tChangedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tChangedAt\x12\x1b\n" +
	"\x06Reason\x18\x03 \x01(\tH\x00R\x06Reason\x88\x01\x01B\t\n" +
	"\a_ReasonB:Z8github.com/sologenic/com-fs-utils-lib/models/audit;auditb\x06proto3"

var (
	file_audit_audit_proto_rawDescOnce sync.Once
	file_audit_audit_proto_rawDescData []byte
)

func file_audit_audit_proto_rawDescGZIP() []byte {
	file_audit_audit_proto_rawDescOnce.Do(func() {
		file_audit_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_audit_proto_rawDesc), len(file_audit_audit_proto_rawDesc)))
	})
	return file_audit_audit_proto_rawDescData
}

var file_audit_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_audit_audit_proto_goTypes = []any{
	(*Audit)(nil),                 // 0: audit.Audit
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_audit_audit_proto_depIdxs = []int32{
	1, // 0: audit.Audit.ChangedAt:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_audit_audit_proto_init() }
func file_audit_audit_proto_init() {
	if File_audit_audit_proto != nil {
		return
	}
	file_audit_audit_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_audit_proto_rawDesc), len(file_audit_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_audit_audit_proto_goTypes,
		DependencyIndexes: file_audit_audit_proto_depIdxs,
		MessageInfos:      file_audit_audit_proto_msgTypes,
	}.Build()
	File_audit_audit_proto = out.File
	file_audit_audit_proto_goTypes = nil
	file_audit_audit_proto_depIdxs = nil
}
