// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.32.1
// source: http-method/http-method.proto

/* eslint-disable */

export const protobufPackage = "httpmethod";

export enum Method {
  GET = 0,
  POST = 1,
  PUT = 2,
  DELETE = 3,
  UNRECOGNIZED = -1,
}

export function methodFromJSON(object: any): Method {
  switch (object) {
    case 0:
    case "GET":
      return Method.GET;
    case 1:
    case "POST":
      return Method.POST;
    case 2:
    case "PUT":
      return Method.PUT;
    case 3:
    case "DELETE":
      return Method.DELETE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Method.UNRECOGNIZED;
  }
}

export function methodToJSON(object: Method): string {
  switch (object) {
    case Method.GET:
      return "GET";
    case Method.POST:
      return "POST";
    case Method.PUT:
      return "PUT";
    case Method.DELETE:
      return "DELETE";
    case Method.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
