// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v6.32.0
// source: http-method/http-method.proto

package httpmethod

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Method int32

const (
	Method_GET    Method = 0
	Method_POST   Method = 1
	Method_PUT    Method = 2
	Method_DELETE Method = 3
)

// Enum value maps for Method.
var (
	Method_name = map[int32]string{
		0: "GET",
		1: "POST",
		2: "PUT",
		3: "DELETE",
	}
	Method_value = map[string]int32{
		"GET":    0,
		"POST":   1,
		"PUT":    2,
		"DELETE": 3,
	}
)

func (x Method) Enum() *Method {
	p := new(Method)
	*p = x
	return p
}

func (x Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Method) Descriptor() protoreflect.EnumDescriptor {
	return file_http_method_http_method_proto_enumTypes[0].Descriptor()
}

func (Method) Type() protoreflect.EnumType {
	return &file_http_method_http_method_proto_enumTypes[0]
}

func (x Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Method.Descriptor instead.
func (Method) EnumDescriptor() ([]byte, []int) {
	return file_http_method_http_method_proto_rawDescGZIP(), []int{0}
}

var File_http_method_http_method_proto protoreflect.FileDescriptor

var file_http_method_http_method_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x68, 0x74, 0x74, 0x70, 0x2d, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x2f, 0x68, 0x74,
	0x74, 0x70, 0x2d, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x68, 0x74, 0x74, 0x70, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x2a, 0x30, 0x0a, 0x06, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45, 0x54, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x50, 0x4f, 0x53, 0x54, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x55, 0x54, 0x10,
	0x02, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x03, 0x42, 0x45, 0x5a,
	0x43, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x6c, 0x6f,
	0x67, 0x65, 0x6e, 0x69, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x2d, 0x66, 0x73, 0x2d, 0x75, 0x74, 0x69,
	0x6c, 0x73, 0x2d, 0x6c, 0x69, 0x62, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x68, 0x74,
	0x74, 0x70, 0x2d, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x3b, 0x68, 0x74, 0x74, 0x70, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_http_method_http_method_proto_rawDescOnce sync.Once
	file_http_method_http_method_proto_rawDescData = file_http_method_http_method_proto_rawDesc
)

func file_http_method_http_method_proto_rawDescGZIP() []byte {
	file_http_method_http_method_proto_rawDescOnce.Do(func() {
		file_http_method_http_method_proto_rawDescData = protoimpl.X.CompressGZIP(file_http_method_http_method_proto_rawDescData)
	})
	return file_http_method_http_method_proto_rawDescData
}

var file_http_method_http_method_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_http_method_http_method_proto_goTypes = []interface{}{
	(Method)(0), // 0: httpmethod.Method
}
var file_http_method_http_method_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_http_method_http_method_proto_init() }
func file_http_method_http_method_proto_init() {
	if File_http_method_http_method_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_http_method_http_method_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_http_method_http_method_proto_goTypes,
		DependencyIndexes: file_http_method_http_method_proto_depIdxs,
		EnumInfos:         file_http_method_http_method_proto_enumTypes,
	}.Build()
	File_http_method_http_method_proto = out.File
	file_http_method_http_method_proto_rawDesc = nil
	file_http_method_http_method_proto_goTypes = nil
	file_http_method_http_method_proto_depIdxs = nil
}
