// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: http-method/http-method.proto

package httpmethod

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Method int32

const (
	Method_GET    Method = 0
	Method_POST   Method = 1
	Method_PUT    Method = 2
	Method_DELETE Method = 3
)

// Enum value maps for Method.
var (
	Method_name = map[int32]string{
		0: "GET",
		1: "POST",
		2: "PUT",
		3: "DELETE",
	}
	Method_value = map[string]int32{
		"GET":    0,
		"POST":   1,
		"PUT":    2,
		"DELETE": 3,
	}
)

func (x Method) Enum() *Method {
	p := new(Method)
	*p = x
	return p
}

func (x Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Method) Descriptor() protoreflect.EnumDescriptor {
	return file_http_method_http_method_proto_enumTypes[0].Descriptor()
}

func (Method) Type() protoreflect.EnumType {
	return &file_http_method_http_method_proto_enumTypes[0]
}

func (x Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Method.Descriptor instead.
func (Method) EnumDescriptor() ([]byte, []int) {
	return file_http_method_http_method_proto_rawDescGZIP(), []int{0}
}

var File_http_method_http_method_proto protoreflect.FileDescriptor

const file_http_method_http_method_proto_rawDesc = "" +
	"\n" +
	"\x1dhttp-method/http-method.proto\x12\n" +
	"httpmethod*0\n" +
	"\x06Method\x12\a\n" +
	"\x03GET\x10\x00\x12\b\n" +
	"\x04POST\x10\x01\x12\a\n" +
	"\x03PUT\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03BEZCgithub.com/sologenic/com-fs-utils-lib/models/http-method;httpmethodb\x06proto3"

var (
	file_http_method_http_method_proto_rawDescOnce sync.Once
	file_http_method_http_method_proto_rawDescData []byte
)

func file_http_method_http_method_proto_rawDescGZIP() []byte {
	file_http_method_http_method_proto_rawDescOnce.Do(func() {
		file_http_method_http_method_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_http_method_http_method_proto_rawDesc), len(file_http_method_http_method_proto_rawDesc)))
	})
	return file_http_method_http_method_proto_rawDescData
}

var file_http_method_http_method_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_http_method_http_method_proto_goTypes = []any{
	(Method)(0), // 0: httpmethod.Method
}
var file_http_method_http_method_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_http_method_http_method_proto_init() }
func file_http_method_http_method_proto_init() {
	if File_http_method_http_method_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_http_method_http_method_proto_rawDesc), len(file_http_method_http_method_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_http_method_http_method_proto_goTypes,
		DependencyIndexes: file_http_method_http_method_proto_depIdxs,
		EnumInfos:         file_http_method_http_method_proto_enumTypes,
	}.Build()
	File_http_method_http_method_proto = out.File
	file_http_method_http_method_proto_goTypes = nil
	file_http_method_http_method_proto_depIdxs = nil
}
