// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: commission/commission.proto

package commission

import (
	decimal "github.com/sologenic/com-fs-utils-lib/go/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommissionType int32

const (
	CommissionType_NOT_USED_COMMISSION_TYPE CommissionType = 0
	CommissionType_NOTIONAL                 CommissionType = 1 // Charge commission on a per order basis (default)
	CommissionType_QTY                      CommissionType = 2 // Charge commission on a per qty/contract basis, pro rated
	CommissionType_BPS                      CommissionType = 3 // Commission expressed in basis points (percent), converted to notional amount for purposes of calculating commission(max two decimal places)
)

// Enum value maps for CommissionType.
var (
	CommissionType_name = map[int32]string{
		0: "NOT_USED_COMMISSION_TYPE",
		1: "NOTIONAL",
		2: "QTY",
		3: "BPS",
	}
	CommissionType_value = map[string]int32{
		"NOT_USED_COMMISSION_TYPE": 0,
		"NOTIONAL":                 1,
		"QTY":                      2,
		"BPS":                      3,
	}
)

func (x CommissionType) Enum() *CommissionType {
	p := new(CommissionType)
	*p = x
	return p
}

func (x CommissionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommissionType) Descriptor() protoreflect.EnumDescriptor {
	return file_commission_commission_proto_enumTypes[0].Descriptor()
}

func (CommissionType) Type() protoreflect.EnumType {
	return &file_commission_commission_proto_enumTypes[0]
}

func (x CommissionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommissionType.Descriptor instead.
func (CommissionType) EnumDescriptor() ([]byte, []int) {
	return file_commission_commission_proto_rawDescGZIP(), []int{0}
}

// Broker API specific commission fields for user level (overrrides organization level)
type CommissionSettings struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Commission     *decimal.Decimal       `protobuf:"bytes,25,opt,name=Commission,proto3,oneof" json:"Commission,omitempty"`                                         // Commission charged for the order
	CommissionType *CommissionType        `protobuf:"varint,26,opt,name=CommissionType,proto3,enum=commission.CommissionType,oneof" json:"CommissionType,omitempty"` // How commission field value is calculated
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommissionSettings) Reset() {
	*x = CommissionSettings{}
	mi := &file_commission_commission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommissionSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommissionSettings) ProtoMessage() {}

func (x *CommissionSettings) ProtoReflect() protoreflect.Message {
	mi := &file_commission_commission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommissionSettings.ProtoReflect.Descriptor instead.
func (*CommissionSettings) Descriptor() ([]byte, []int) {
	return file_commission_commission_proto_rawDescGZIP(), []int{0}
}

func (x *CommissionSettings) GetCommission() *decimal.Decimal {
	if x != nil {
		return x.Commission
	}
	return nil
}

func (x *CommissionSettings) GetCommissionType() CommissionType {
	if x != nil && x.CommissionType != nil {
		return *x.CommissionType
	}
	return CommissionType_NOT_USED_COMMISSION_TYPE
}

var File_commission_commission_proto protoreflect.FileDescriptor

const file_commission_commission_proto_rawDesc = "" +
	"\n" +
	"\x1bcommission/commission.proto\x12\n" +
	"commission\x1a3sologenic/com-fs-utils-lib/go/decimal/decimal.proto\"\xb6\x01\n" +
	"\x12CommissionSettings\x125\n" +
	"\n" +
	"Commission\x18\x19 \x01(\v2\x10.decimal.DecimalH\x00R\n" +
	"Commission\x88\x01\x01\x12G\n" +
	"\x0eCommissionType\x18\x1a \x01(\x0e2\x1a.commission.CommissionTypeH\x01R\x0eCommissionType\x88\x01\x01B\r\n" +
	"\v_CommissionB\x11\n" +
	"\x0f_CommissionType*N\n" +
	"\x0eCommissionType\x12\x1c\n" +
	"\x18NOT_USED_COMMISSION_TYPE\x10\x00\x12\f\n" +
	"\bNOTIONAL\x10\x01\x12\a\n" +
	"\x03QTY\x10\x02\x12\a\n" +
	"\x03BPS\x10\x03BDZBgithub.com/sologenic/com-fs-utils-lib/models/commission;commissionb\x06proto3"

var (
	file_commission_commission_proto_rawDescOnce sync.Once
	file_commission_commission_proto_rawDescData []byte
)

func file_commission_commission_proto_rawDescGZIP() []byte {
	file_commission_commission_proto_rawDescOnce.Do(func() {
		file_commission_commission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commission_commission_proto_rawDesc), len(file_commission_commission_proto_rawDesc)))
	})
	return file_commission_commission_proto_rawDescData
}

var file_commission_commission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_commission_commission_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_commission_commission_proto_goTypes = []any{
	(CommissionType)(0),        // 0: commission.CommissionType
	(*CommissionSettings)(nil), // 1: commission.CommissionSettings
	(*decimal.Decimal)(nil),    // 2: decimal.Decimal
}
var file_commission_commission_proto_depIdxs = []int32{
	2, // 0: commission.CommissionSettings.Commission:type_name -> decimal.Decimal
	0, // 1: commission.CommissionSettings.CommissionType:type_name -> commission.CommissionType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_commission_commission_proto_init() }
func file_commission_commission_proto_init() {
	if File_commission_commission_proto != nil {
		return
	}
	file_commission_commission_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commission_commission_proto_rawDesc), len(file_commission_commission_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commission_commission_proto_goTypes,
		DependencyIndexes: file_commission_commission_proto_depIdxs,
		EnumInfos:         file_commission_commission_proto_enumTypes,
		MessageInfos:      file_commission_commission_proto_msgTypes,
	}.Build()
	File_commission_commission_proto = out.File
	file_commission_commission_proto_goTypes = nil
	file_commission_commission_proto_depIdxs = nil
}
