syntax = "proto3";

package commission;

option go_package = "github.com/sologenic/com-fs-utils-lib/models/commission;commission";

import "sologenic/com-fs-utils-lib/models/decimal/decimal.proto";
import "buf/validate/validate.proto";

// Broker API specific commission fields for user level (overrrides organization level)
message CommissionSettings {
  optional decimal.Decimal Commission = 25 [
    (buf.validate.field).required = true,
    (buf.validate.field).cel = {
      id: "commission_settings.commission.range"
      message: "Commission must be between 0 and 10000 with at most 2 fraction digits"
      expression: "this.Value >= 0 && this.Value <= 10000 && this.Exp >= -2 && this.Exp <= 0"
    }
  ]; // Commission charged for the order
  optional CommissionType CommissionType = 26 [
    (buf.validate.field).required = true,
    (buf.validate.field).enum = {
      defined_only: true
      not_in: [0]
    }
  ]; // How commission field value is calculated
}

enum CommissionType {
  NOT_USED_COMMISSION_TYPE = 0;
  NOTIONAL = 1; // Charge commission on a per order basis (default)
  QTY = 2; // Charge commission on a per qty/contract basis, pro rated
  BPS = 3; // Commission expressed in basis points (percent), converted to notional amount for purposes of calculating commission(max two decimal places)
}