// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: commission/commission.proto

package commission

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	decimal "github.com/sologenic/com-fs-utils-lib/models/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// CommissionType defines the specific method used to interpret and calculate
// the commission charged to the end user for a given order.
//
// SUBMISSION GUIDELINES:
// When submitting an order, the actual commission value must be provided alongside
// this enum as a string representing a numeric value (e.g., "1.50") to prevent
// floating-point precision loss.
type CommissionType int32

const (
	CommissionType_NOT_USED_COMMISSION_TYPE CommissionType = 0
	// Charge commission on a fixed per-order basis.
	// The submitted string value is applied as a flat fee for the entire order,
	// regardless of the quantity of shares or contracts executed.
	//
	// Example Submission:
	// - Submitted Value: "2.50"
	// - Result: A flat $2.50 commission is collected for the order.
	CommissionType_NOTIONAL CommissionType = 1
	// Charge commission on a per-quantity or per-contract basis, pro-rated.
	// The total commission is calculated by multiplying the executed order quantity
	// by the submitted string value.
	//
	// Example Submission:
	// - Submitted Value: "0.05"
	// - Order Quantity: 100 shares
	// - Result: $5.00 total commission (100 * 0.05).
	CommissionType_QTY CommissionType = 2
	// Charge commission in basis points (BPS).
	// The commission is calculated as a percentage of the total notional value
	// of the order. 1 basis point equals 0.01% (or 0.0001).
	// The system automatically converts the order to a notional amount to
	// calculate the final fee. The submitted BPS value can have up to two decimal places.
	//
	// Example Submission:
	// - Submitted Value: "12.50" (representing 12.50 bps or 0.125%)
	// - Order Notional Value: $10,000
	// - Result: $12.50 total commission ($10,000 * 0.125%).
	CommissionType_BPS CommissionType = 3
)

// Enum value maps for CommissionType.
var (
	CommissionType_name = map[int32]string{
		0: "NOT_USED_COMMISSION_TYPE",
		1: "NOTIONAL",
		2: "QTY",
		3: "BPS",
	}
	CommissionType_value = map[string]int32{
		"NOT_USED_COMMISSION_TYPE": 0,
		"NOTIONAL":                 1,
		"QTY":                      2,
		"BPS":                      3,
	}
)

func (x CommissionType) Enum() *CommissionType {
	p := new(CommissionType)
	*p = x
	return p
}

func (x CommissionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommissionType) Descriptor() protoreflect.EnumDescriptor {
	return file_commission_commission_proto_enumTypes[0].Descriptor()
}

func (CommissionType) Type() protoreflect.EnumType {
	return &file_commission_commission_proto_enumTypes[0]
}

func (x CommissionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommissionType.Descriptor instead.
func (CommissionType) EnumDescriptor() ([]byte, []int) {
	return file_commission_commission_proto_rawDescGZIP(), []int{0}
}

// Broker API specific commission fields for user level (overrrides organization level)
type CommissionSettings struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Commission     *decimal.Decimal       `protobuf:"bytes,25,opt,name=Commission,proto3" json:"Commission,omitempty"`
	CommissionType CommissionType         `protobuf:"varint,26,opt,name=CommissionType,proto3,enum=commission.CommissionType" json:"CommissionType,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommissionSettings) Reset() {
	*x = CommissionSettings{}
	mi := &file_commission_commission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommissionSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommissionSettings) ProtoMessage() {}

func (x *CommissionSettings) ProtoReflect() protoreflect.Message {
	mi := &file_commission_commission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommissionSettings.ProtoReflect.Descriptor instead.
func (*CommissionSettings) Descriptor() ([]byte, []int) {
	return file_commission_commission_proto_rawDescGZIP(), []int{0}
}

func (x *CommissionSettings) GetCommission() *decimal.Decimal {
	if x != nil {
		return x.Commission
	}
	return nil
}

func (x *CommissionSettings) GetCommissionType() CommissionType {
	if x != nil {
		return x.CommissionType
	}
	return CommissionType_NOT_USED_COMMISSION_TYPE
}

var File_commission_commission_proto protoreflect.FileDescriptor

const file_commission_commission_proto_rawDesc = "" +
	"\n" +
	"\x1bcommission/commission.proto\x12\n" +
	"commission\x1a7sologenic/com-fs-utils-lib/models/decimal/decimal.proto\x1a\x1bbuf/validate/validate.proto\"\x8f\x11\n" +
	"\x12CommissionSettings\x128\n" +
	"\n" +
	"Commission\x18\x19 \x01(\v2\x10.decimal.DecimalB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"Commission\x12N\n" +
	"\x0eCommissionType\x18\x1a \x01(\x0e2\x1a.commission.CommissionTypeB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x0eCommissionType:\xee\x0f\xbaH\xea\x0f\x1a\xa7\x05\n" +
	"\"commission_settings.notional.range\x12NNOTIONAL commission must be between 0 and 10000 with at most 2 fraction digits\x1a\xb0\x04this.CommissionType != 1 || (this.Commission.Value >= 0 && this.Commission.Exp >= -2 && (this.Commission.Value == 0 || (this.Commission.Exp == -2 && this.Commission.Value <= 1000000) || (this.Commission.Exp == -1 && this.Commission.Value <= 100000) || (this.Commission.Exp == 0 && this.Commission.Value <= 10000) || (this.Commission.Exp == 1 && this.Commission.Value <= 1000) || (this.Commission.Exp == 2 && this.Commission.Value <= 100) || (this.Commission.Exp == 3 && this.Commission.Value <= 10) || (this.Commission.Exp == 4 && this.Commission.Value <= 1)))\x1a\x9d\x05\n" +
	"\x1dcommission_settings.qty.range\x12IQTY commission must be between 0 and 10000 with at most 2 fraction digits\x1a\xb0\x04this.CommissionType != 2 || (this.Commission.Value >= 0 && this.Commission.Exp >= -2 && (this.Commission.Value == 0 || (this.Commission.Exp == -2 && this.Commission.Value <= 1000000) || (this.Commission.Exp == -1 && this.Commission.Value <= 100000) || (this.Commission.Exp == 0 && this.Commission.Value <= 10000) || (this.Commission.Exp == 1 && this.Commission.Value <= 1000) || (this.Commission.Exp == 2 && this.Commission.Value <= 100) || (this.Commission.Exp == 3 && this.Commission.Value <= 10) || (this.Commission.Exp == 4 && this.Commission.Value <= 1)))\x1a\x9d\x05\n" +
	"\x1dcommission_settings.bps.range\x12IBPS commission must be between 0 and 10000 with at most 2 fraction digits\x1a\xb0\x04this.CommissionType != 3 || (this.Commission.Value >= 0 && this.Commission.Exp >= -2 && (this.Commission.Value == 0 || (this.Commission.Exp == -2 && this.Commission.Value <= 1000000) || (this.Commission.Exp == -1 && this.Commission.Value <= 100000) || (this.Commission.Exp == 0 && this.Commission.Value <= 10000) || (this.Commission.Exp == 1 && this.Commission.Value <= 1000) || (this.Commission.Exp == 2 && this.Commission.Value <= 100) || (this.Commission.Exp == 3 && this.Commission.Value <= 10) || (this.Commission.Exp == 4 && this.Commission.Value <= 1)))*N\n" +
	"\x0eCommissionType\x12\x1c\n" +
	"\x18NOT_USED_COMMISSION_TYPE\x10\x00\x12\f\n" +
	"\bNOTIONAL\x10\x01\x12\a\n" +
	"\x03QTY\x10\x02\x12\a\n" +
	"\x03BPS\x10\x03BDZBgithub.com/sologenic/com-fs-utils-lib/models/commission;commissionb\x06proto3"

var (
	file_commission_commission_proto_rawDescOnce sync.Once
	file_commission_commission_proto_rawDescData []byte
)

func file_commission_commission_proto_rawDescGZIP() []byte {
	file_commission_commission_proto_rawDescOnce.Do(func() {
		file_commission_commission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commission_commission_proto_rawDesc), len(file_commission_commission_proto_rawDesc)))
	})
	return file_commission_commission_proto_rawDescData
}

var file_commission_commission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_commission_commission_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_commission_commission_proto_goTypes = []any{
	(CommissionType)(0),        // 0: commission.CommissionType
	(*CommissionSettings)(nil), // 1: commission.CommissionSettings
	(*decimal.Decimal)(nil),    // 2: decimal.Decimal
}
var file_commission_commission_proto_depIdxs = []int32{
	2, // 0: commission.CommissionSettings.Commission:type_name -> decimal.Decimal
	0, // 1: commission.CommissionSettings.CommissionType:type_name -> commission.CommissionType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_commission_commission_proto_init() }
func file_commission_commission_proto_init() {
	if File_commission_commission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commission_commission_proto_rawDesc), len(file_commission_commission_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commission_commission_proto_goTypes,
		DependencyIndexes: file_commission_commission_proto_depIdxs,
		EnumInfos:         file_commission_commission_proto_enumTypes,
		MessageInfos:      file_commission_commission_proto_msgTypes,
	}.Build()
	File_commission_commission_proto = out.File
	file_commission_commission_proto_goTypes = nil
	file_commission_commission_proto_depIdxs = nil
}
