// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v6.32.0
// source: commission/commission.proto

package commission

import (
	decimal "github.com/sologenic/com-fs-utils-lib/models/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommissionType int32

const (
	CommissionType_NOT_USED_COMMISSION_TYPE CommissionType = 0
	CommissionType_NOTIONAL                 CommissionType = 1 // Charge commission on a per order basis (default)
	CommissionType_QTY                      CommissionType = 2 // Charge commission on a per qty/contract basis, pro rated
	CommissionType_BPS                      CommissionType = 3 // Commission expressed in basis points (percent), converted to notional amount for purposes of calculating commission(max two decimal places)
)

// Enum value maps for CommissionType.
var (
	CommissionType_name = map[int32]string{
		0: "NOT_USED_COMMISSION_TYPE",
		1: "NOTIONAL",
		2: "QTY",
		3: "BPS",
	}
	CommissionType_value = map[string]int32{
		"NOT_USED_COMMISSION_TYPE": 0,
		"NOTIONAL":                 1,
		"QTY":                      2,
		"BPS":                      3,
	}
)

func (x CommissionType) Enum() *CommissionType {
	p := new(CommissionType)
	*p = x
	return p
}

func (x CommissionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommissionType) Descriptor() protoreflect.EnumDescriptor {
	return file_commission_commission_proto_enumTypes[0].Descriptor()
}

func (CommissionType) Type() protoreflect.EnumType {
	return &file_commission_commission_proto_enumTypes[0]
}

func (x CommissionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommissionType.Descriptor instead.
func (CommissionType) EnumDescriptor() ([]byte, []int) {
	return file_commission_commission_proto_rawDescGZIP(), []int{0}
}

// Broker API specific commission fields for user level (overrrides organization level)
type CommissionSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commission     *decimal.Decimal `protobuf:"bytes,25,opt,name=Commission,proto3,oneof" json:"Commission,omitempty"`                                         // Commission charged for the order
	CommissionType *CommissionType  `protobuf:"varint,26,opt,name=CommissionType,proto3,enum=commission.CommissionType,oneof" json:"CommissionType,omitempty"` // How commission field value is calculated
}

func (x *CommissionSettings) Reset() {
	*x = CommissionSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commission_commission_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommissionSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommissionSettings) ProtoMessage() {}

func (x *CommissionSettings) ProtoReflect() protoreflect.Message {
	mi := &file_commission_commission_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommissionSettings.ProtoReflect.Descriptor instead.
func (*CommissionSettings) Descriptor() ([]byte, []int) {
	return file_commission_commission_proto_rawDescGZIP(), []int{0}
}

func (x *CommissionSettings) GetCommission() *decimal.Decimal {
	if x != nil {
		return x.Commission
	}
	return nil
}

func (x *CommissionSettings) GetCommissionType() CommissionType {
	if x != nil && x.CommissionType != nil {
		return *x.CommissionType
	}
	return CommissionType_NOT_USED_COMMISSION_TYPE
}

var File_commission_commission_proto protoreflect.FileDescriptor

var file_commission_commission_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x15, 0x64, 0x65, 0x63, 0x69, 0x6d,
	0x61, 0x6c, 0x2f, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xb6, 0x01, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x35, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x19, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x65,
	0x63, 0x69, 0x6d, 0x61, 0x6c, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x48, 0x00, 0x52,
	0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x47,
	0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x1a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x48, 0x01, 0x52, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x2a, 0x4e, 0x0a, 0x0e, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x4e,
	0x4f, 0x54, 0x5f, 0x55, 0x53, 0x45, 0x44, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x49, 0x53, 0x53, 0x49,
	0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x54,
	0x49, 0x4f, 0x4e, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x51, 0x54, 0x59, 0x10, 0x02,
	0x12, 0x07, 0x0a, 0x03, 0x42, 0x50, 0x53, 0x10, 0x03, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x6c, 0x6f, 0x67, 0x65, 0x6e, 0x69,
	0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x2d, 0x66, 0x73, 0x2d, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2d, 0x6c,
	0x69, 0x62, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_commission_commission_proto_rawDescOnce sync.Once
	file_commission_commission_proto_rawDescData = file_commission_commission_proto_rawDesc
)

func file_commission_commission_proto_rawDescGZIP() []byte {
	file_commission_commission_proto_rawDescOnce.Do(func() {
		file_commission_commission_proto_rawDescData = protoimpl.X.CompressGZIP(file_commission_commission_proto_rawDescData)
	})
	return file_commission_commission_proto_rawDescData
}

var file_commission_commission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_commission_commission_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_commission_commission_proto_goTypes = []interface{}{
	(CommissionType)(0),        // 0: commission.CommissionType
	(*CommissionSettings)(nil), // 1: commission.CommissionSettings
	(*decimal.Decimal)(nil),    // 2: decimal.Decimal
}
var file_commission_commission_proto_depIdxs = []int32{
	2, // 0: commission.CommissionSettings.Commission:type_name -> decimal.Decimal
	0, // 1: commission.CommissionSettings.CommissionType:type_name -> commission.CommissionType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_commission_commission_proto_init() }
func file_commission_commission_proto_init() {
	if File_commission_commission_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_commission_commission_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommissionSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_commission_commission_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_commission_commission_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commission_commission_proto_goTypes,
		DependencyIndexes: file_commission_commission_proto_depIdxs,
		EnumInfos:         file_commission_commission_proto_enumTypes,
		MessageInfos:      file_commission_commission_proto_msgTypes,
	}.Build()
	File_commission_commission_proto = out.File
	file_commission_commission_proto_rawDesc = nil
	file_commission_commission_proto_goTypes = nil
	file_commission_commission_proto_depIdxs = nil
}
