// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.32.0
// source: order-properties/order-properties.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "orderproperties";

/** Side is order side. */
export enum Side {
  /** SIDE_NOT_APPLICABLE - SIDE_NOT_APPLICABLE reserves the default value, to protect against unexpected settings. */
  SIDE_NOT_APPLICABLE = 0,
  /** SIDE_BUY - SIDE_BUY means that the order is to buy base_denom quantity with the price. */
  SIDE_BUY = 1,
  /** SIDE_SELL - SIDE_SELL means that the order is to sell base_denom quantity with the price. */
  SIDE_SELL = 2,
  UNRECOGNIZED = -1,
}

export function sideFromJSON(object: any): Side {
  switch (object) {
    case 0:
    case "SIDE_NOT_APPLICABLE":
      return Side.SIDE_NOT_APPLICABLE;
    case 1:
    case "SIDE_BUY":
      return Side.SIDE_BUY;
    case 2:
    case "SIDE_SELL":
      return Side.SIDE_SELL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Side.UNRECOGNIZED;
  }
}

export function sideToJSON(object: Side): string {
  switch (object) {
    case Side.SIDE_NOT_APPLICABLE:
      return "SIDE_NOT_APPLICABLE";
    case Side.SIDE_BUY:
      return "SIDE_BUY";
    case Side.SIDE_SELL:
      return "SIDE_SELL";
    case Side.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum TimeInForce {
  NOT_USED_TIME_IN_FORCE = 0,
  DAY = 1,
  /** GOOD_TIL_CANCELED - GTC */
  GOOD_TIL_CANCELED = 2,
  /** AT_THE_OPENING - OPG */
  AT_THE_OPENING = 3,
  /** AT_THE_CLOSE - CLS */
  AT_THE_CLOSE = 4,
  /** IMMEDIATE_OR_CANCEL - IOC */
  IMMEDIATE_OR_CANCEL = 5,
  /** FILL_OR_KILL - FOK */
  FILL_OR_KILL = 6,
  /** GOOD_TIL_TIME - GTT */
  GOOD_TIL_TIME = 7,
  UNRECOGNIZED = -1,
}

export function timeInForceFromJSON(object: any): TimeInForce {
  switch (object) {
    case 0:
    case "NOT_USED_TIME_IN_FORCE":
      return TimeInForce.NOT_USED_TIME_IN_FORCE;
    case 1:
    case "DAY":
      return TimeInForce.DAY;
    case 2:
    case "GOOD_TIL_CANCELED":
      return TimeInForce.GOOD_TIL_CANCELED;
    case 3:
    case "AT_THE_OPENING":
      return TimeInForce.AT_THE_OPENING;
    case 4:
    case "AT_THE_CLOSE":
      return TimeInForce.AT_THE_CLOSE;
    case 5:
    case "IMMEDIATE_OR_CANCEL":
      return TimeInForce.IMMEDIATE_OR_CANCEL;
    case 6:
    case "FILL_OR_KILL":
      return TimeInForce.FILL_OR_KILL;
    case 7:
    case "GOOD_TIL_TIME":
      return TimeInForce.GOOD_TIL_TIME;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TimeInForce.UNRECOGNIZED;
  }
}

export function timeInForceToJSON(object: TimeInForce): string {
  switch (object) {
    case TimeInForce.NOT_USED_TIME_IN_FORCE:
      return "NOT_USED_TIME_IN_FORCE";
    case TimeInForce.DAY:
      return "DAY";
    case TimeInForce.GOOD_TIL_CANCELED:
      return "GOOD_TIL_CANCELED";
    case TimeInForce.AT_THE_OPENING:
      return "AT_THE_OPENING";
    case TimeInForce.AT_THE_CLOSE:
      return "AT_THE_CLOSE";
    case TimeInForce.IMMEDIATE_OR_CANCEL:
      return "IMMEDIATE_OR_CANCEL";
    case TimeInForce.FILL_OR_KILL:
      return "FILL_OR_KILL";
    case TimeInForce.GOOD_TIL_TIME:
      return "GOOD_TIL_TIME";
    case TimeInForce.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum OrderType {
  /** NOT_APPLICABLE_ORDER_TYPE - Changed not used to NOT_APPLICABLE_ORDER_TYPE to avoid naming conflicts with PURCHASE in the action enum */
  NOT_APPLICABLE_ORDER_TYPE = 0,
  /** ORDER_TYPE_PURCHASE - Avoid naming conflicts with PURCHASE in the action enum */
  ORDER_TYPE_PURCHASE = 1,
  ORDER_TYPE_SELL = 2,
  UNRECOGNIZED = -1,
}

export function orderTypeFromJSON(object: any): OrderType {
  switch (object) {
    case 0:
    case "NOT_APPLICABLE_ORDER_TYPE":
      return OrderType.NOT_APPLICABLE_ORDER_TYPE;
    case 1:
    case "ORDER_TYPE_PURCHASE":
      return OrderType.ORDER_TYPE_PURCHASE;
    case 2:
    case "ORDER_TYPE_SELL":
      return OrderType.ORDER_TYPE_SELL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OrderType.UNRECOGNIZED;
  }
}

export function orderTypeToJSON(object: OrderType): string {
  switch (object) {
    case OrderType.NOT_APPLICABLE_ORDER_TYPE:
      return "NOT_APPLICABLE_ORDER_TYPE";
    case OrderType.ORDER_TYPE_PURCHASE:
      return "ORDER_TYPE_PURCHASE";
    case OrderType.ORDER_TYPE_SELL:
      return "ORDER_TYPE_SELL";
    case OrderType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ProcessState {
  NOT_USED_PROCESS_STATE = 0,
  PROCESS_STATE_OPEN = 1,
  PROCESS_STATE_LOCKED = 2,
  PROCESS_STATE_FAILED = 3,
  PROCESS_STATE_PROCESSED = 4,
  UNRECOGNIZED = -1,
}

export function processStateFromJSON(object: any): ProcessState {
  switch (object) {
    case 0:
    case "NOT_USED_PROCESS_STATE":
      return ProcessState.NOT_USED_PROCESS_STATE;
    case 1:
    case "PROCESS_STATE_OPEN":
      return ProcessState.PROCESS_STATE_OPEN;
    case 2:
    case "PROCESS_STATE_LOCKED":
      return ProcessState.PROCESS_STATE_LOCKED;
    case 3:
    case "PROCESS_STATE_FAILED":
      return ProcessState.PROCESS_STATE_FAILED;
    case 4:
    case "PROCESS_STATE_PROCESSED":
      return ProcessState.PROCESS_STATE_PROCESSED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ProcessState.UNRECOGNIZED;
  }
}

export function processStateToJSON(object: ProcessState): string {
  switch (object) {
    case ProcessState.NOT_USED_PROCESS_STATE:
      return "NOT_USED_PROCESS_STATE";
    case ProcessState.PROCESS_STATE_OPEN:
      return "PROCESS_STATE_OPEN";
    case ProcessState.PROCESS_STATE_LOCKED:
      return "PROCESS_STATE_LOCKED";
    case ProcessState.PROCESS_STATE_FAILED:
      return "PROCESS_STATE_FAILED";
    case ProcessState.PROCESS_STATE_PROCESSED:
      return "PROCESS_STATE_PROCESSED";
    case ProcessState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ClearingBroker {
  NOT_USED_CLEARING_BROKER = 0,
  ALPACA = 1,
  RQD = 2,
  UNRECOGNIZED = -1,
}

export function clearingBrokerFromJSON(object: any): ClearingBroker {
  switch (object) {
    case 0:
    case "NOT_USED_CLEARING_BROKER":
      return ClearingBroker.NOT_USED_CLEARING_BROKER;
    case 1:
    case "ALPACA":
      return ClearingBroker.ALPACA;
    case 2:
    case "RQD":
      return ClearingBroker.RQD;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ClearingBroker.UNRECOGNIZED;
  }
}

export function clearingBrokerToJSON(object: ClearingBroker): string {
  switch (object) {
    case ClearingBroker.NOT_USED_CLEARING_BROKER:
      return "NOT_USED_CLEARING_BROKER";
    case ClearingBroker.ALPACA:
      return "ALPACA";
    case ClearingBroker.RQD:
      return "RQD";
    case ClearingBroker.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface ProcessInfo {
  ProcessState: ProcessState;
  ProcessedAt: Date | undefined;
}

function createBaseProcessInfo(): ProcessInfo {
  return { ProcessState: 0, ProcessedAt: undefined };
}

export const ProcessInfo = {
  encode(message: ProcessInfo, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.ProcessState !== 0) {
      writer.uint32(8).int32(message.ProcessState);
    }
    if (message.ProcessedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.ProcessedAt), writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ProcessInfo {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProcessInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.ProcessState = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.ProcessedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProcessInfo {
    return {
      ProcessState: isSet(object.ProcessState) ? processStateFromJSON(object.ProcessState) : 0,
      ProcessedAt: isSet(object.ProcessedAt) ? fromJsonTimestamp(object.ProcessedAt) : undefined,
    };
  },

  toJSON(message: ProcessInfo): unknown {
    const obj: any = {};
    if (message.ProcessState !== 0) {
      obj.ProcessState = processStateToJSON(message.ProcessState);
    }
    if (message.ProcessedAt !== undefined) {
      obj.ProcessedAt = message.ProcessedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProcessInfo>, I>>(base?: I): ProcessInfo {
    return ProcessInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProcessInfo>, I>>(object: I): ProcessInfo {
    const message = createBaseProcessInfo();
    message.ProcessState = object.ProcessState ?? 0;
    message.ProcessedAt = object.ProcessedAt ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
