// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v6.32.0
// source: order-properties/order-properties.proto

package orderproperties

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Side is order side.
type Side int32

const (
	// SIDE_NOT_APPLICABLE reserves the default value, to protect against unexpected settings.
	Side_SIDE_NOT_APPLICABLE Side = 0
	// SIDE_BUY means that the order is to buy base_denom quantity with the price.
	Side_SIDE_BUY Side = 1
	// SIDE_SELL means that the order is to sell base_denom quantity with the price.
	Side_SIDE_SELL Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_NOT_APPLICABLE",
		1: "SIDE_BUY",
		2: "SIDE_SELL",
	}
	Side_value = map[string]int32{
		"SIDE_NOT_APPLICABLE": 0,
		"SIDE_BUY":            1,
		"SIDE_SELL":           2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_order_properties_order_properties_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_order_properties_order_properties_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_order_properties_order_properties_proto_rawDescGZIP(), []int{0}
}

type TimeInForce int32

const (
	TimeInForce_NOT_USED_TIME_IN_FORCE TimeInForce = 0
	TimeInForce_DAY                    TimeInForce = 1
	TimeInForce_GOOD_TIL_CANCELED      TimeInForce = 2 // GTC
	TimeInForce_AT_THE_OPENING         TimeInForce = 3 // OPG
	TimeInForce_AT_THE_CLOSE           TimeInForce = 4 // CLS
	TimeInForce_IMMEDIATE_OR_CANCEL    TimeInForce = 5 // IOC
	TimeInForce_FILL_OR_KILL           TimeInForce = 6 // FOK
	TimeInForce_GOOD_TIL_TIME          TimeInForce = 7 // GTT
)

// Enum value maps for TimeInForce.
var (
	TimeInForce_name = map[int32]string{
		0: "NOT_USED_TIME_IN_FORCE",
		1: "DAY",
		2: "GOOD_TIL_CANCELED",
		3: "AT_THE_OPENING",
		4: "AT_THE_CLOSE",
		5: "IMMEDIATE_OR_CANCEL",
		6: "FILL_OR_KILL",
		7: "GOOD_TIL_TIME",
	}
	TimeInForce_value = map[string]int32{
		"NOT_USED_TIME_IN_FORCE": 0,
		"DAY":                    1,
		"GOOD_TIL_CANCELED":      2,
		"AT_THE_OPENING":         3,
		"AT_THE_CLOSE":           4,
		"IMMEDIATE_OR_CANCEL":    5,
		"FILL_OR_KILL":           6,
		"GOOD_TIL_TIME":          7,
	}
)

func (x TimeInForce) Enum() *TimeInForce {
	p := new(TimeInForce)
	*p = x
	return p
}

func (x TimeInForce) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeInForce) Descriptor() protoreflect.EnumDescriptor {
	return file_order_properties_order_properties_proto_enumTypes[1].Descriptor()
}

func (TimeInForce) Type() protoreflect.EnumType {
	return &file_order_properties_order_properties_proto_enumTypes[1]
}

func (x TimeInForce) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeInForce.Descriptor instead.
func (TimeInForce) EnumDescriptor() ([]byte, []int) {
	return file_order_properties_order_properties_proto_rawDescGZIP(), []int{1}
}

type OrderType int32

const (
	//Changed not used to NOT_APPLICABLE_ORDER_TYPE to avoid naming conflicts with PURCHASE in the action enum
	OrderType_NOT_APPLICABLE_ORDER_TYPE OrderType = 0
	OrderType_ORDER_TYPE_PURCHASE       OrderType = 1 // Avoid naming conflicts with PURCHASE in the action enum
	OrderType_ORDER_TYPE_SELL           OrderType = 2
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "NOT_APPLICABLE_ORDER_TYPE",
		1: "ORDER_TYPE_PURCHASE",
		2: "ORDER_TYPE_SELL",
	}
	OrderType_value = map[string]int32{
		"NOT_APPLICABLE_ORDER_TYPE": 0,
		"ORDER_TYPE_PURCHASE":       1,
		"ORDER_TYPE_SELL":           2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_order_properties_order_properties_proto_enumTypes[2].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_order_properties_order_properties_proto_enumTypes[2]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_order_properties_order_properties_proto_rawDescGZIP(), []int{2}
}

type ProcessState int32

const (
	ProcessState_NOT_USED_PROCESS_STATE  ProcessState = 0
	ProcessState_PROCESS_STATE_OPEN      ProcessState = 1
	ProcessState_PROCESS_STATE_LOCKED    ProcessState = 2
	ProcessState_PROCESS_STATE_FAILED    ProcessState = 3
	ProcessState_PROCESS_STATE_PROCESSED ProcessState = 4
)

// Enum value maps for ProcessState.
var (
	ProcessState_name = map[int32]string{
		0: "NOT_USED_PROCESS_STATE",
		1: "PROCESS_STATE_OPEN",
		2: "PROCESS_STATE_LOCKED",
		3: "PROCESS_STATE_FAILED",
		4: "PROCESS_STATE_PROCESSED",
	}
	ProcessState_value = map[string]int32{
		"NOT_USED_PROCESS_STATE":  0,
		"PROCESS_STATE_OPEN":      1,
		"PROCESS_STATE_LOCKED":    2,
		"PROCESS_STATE_FAILED":    3,
		"PROCESS_STATE_PROCESSED": 4,
	}
)

func (x ProcessState) Enum() *ProcessState {
	p := new(ProcessState)
	*p = x
	return p
}

func (x ProcessState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessState) Descriptor() protoreflect.EnumDescriptor {
	return file_order_properties_order_properties_proto_enumTypes[3].Descriptor()
}

func (ProcessState) Type() protoreflect.EnumType {
	return &file_order_properties_order_properties_proto_enumTypes[3]
}

func (x ProcessState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessState.Descriptor instead.
func (ProcessState) EnumDescriptor() ([]byte, []int) {
	return file_order_properties_order_properties_proto_rawDescGZIP(), []int{3}
}

type ClearingBroker int32

const (
	ClearingBroker_NOT_USED_CLEARING_BROKER ClearingBroker = 0
	ClearingBroker_ALPACA                   ClearingBroker = 1
	ClearingBroker_RQD                      ClearingBroker = 2
)

// Enum value maps for ClearingBroker.
var (
	ClearingBroker_name = map[int32]string{
		0: "NOT_USED_CLEARING_BROKER",
		1: "ALPACA",
		2: "RQD",
	}
	ClearingBroker_value = map[string]int32{
		"NOT_USED_CLEARING_BROKER": 0,
		"ALPACA":                   1,
		"RQD":                      2,
	}
)

func (x ClearingBroker) Enum() *ClearingBroker {
	p := new(ClearingBroker)
	*p = x
	return p
}

func (x ClearingBroker) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClearingBroker) Descriptor() protoreflect.EnumDescriptor {
	return file_order_properties_order_properties_proto_enumTypes[4].Descriptor()
}

func (ClearingBroker) Type() protoreflect.EnumType {
	return &file_order_properties_order_properties_proto_enumTypes[4]
}

func (x ClearingBroker) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClearingBroker.Descriptor instead.
func (ClearingBroker) EnumDescriptor() ([]byte, []int) {
	return file_order_properties_order_properties_proto_rawDescGZIP(), []int{4}
}

type ProcessInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessState ProcessState           `protobuf:"varint,1,opt,name=ProcessState,proto3,enum=orderproperties.ProcessState" json:"ProcessState,omitempty"`
	ProcessedAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ProcessedAt,proto3" json:"ProcessedAt,omitempty"`
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_properties_order_properties_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_properties_order_properties_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_order_properties_order_properties_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessInfo) GetProcessState() ProcessState {
	if x != nil {
		return x.ProcessState
	}
	return ProcessState_NOT_USED_PROCESS_STATE
}

func (x *ProcessInfo) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

var File_order_properties_order_properties_proto protoreflect.FileDescriptor

var file_order_properties_order_properties_proto_rawDesc = []byte{
	0x0a, 0x27, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69,
	0x65, 0x73, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8e, 0x01, 0x0a, 0x0b,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x41, 0x0a, 0x0c, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1d, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x0c, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x3c,
	0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x41, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0b, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x41, 0x74, 0x2a, 0x3c, 0x0a, 0x04,
	0x53, 0x69, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x49, 0x44, 0x45, 0x5f, 0x4e, 0x4f, 0x54,
	0x5f, 0x41, 0x50, 0x50, 0x4c, 0x49, 0x43, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x53, 0x49, 0x44, 0x45, 0x5f, 0x42, 0x55, 0x59, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x53,
	0x49, 0x44, 0x45, 0x5f, 0x53, 0x45, 0x4c, 0x4c, 0x10, 0x02, 0x2a, 0xad, 0x01, 0x0a, 0x0b, 0x54,
	0x69, 0x6d, 0x65, 0x49, 0x6e, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x4e, 0x4f,
	0x54, 0x5f, 0x55, 0x53, 0x45, 0x44, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x49, 0x4e, 0x5f, 0x46,
	0x4f, 0x52, 0x43, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x41, 0x59, 0x10, 0x01, 0x12,
	0x15, 0x0a, 0x11, 0x47, 0x4f, 0x4f, 0x44, 0x5f, 0x54, 0x49, 0x4c, 0x5f, 0x43, 0x41, 0x4e, 0x43,
	0x45, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x54, 0x5f, 0x54, 0x48, 0x45,
	0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x54,
	0x5f, 0x54, 0x48, 0x45, 0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x10, 0x04, 0x12, 0x17, 0x0a, 0x13,
	0x49, 0x4d, 0x4d, 0x45, 0x44, 0x49, 0x41, 0x54, 0x45, 0x5f, 0x4f, 0x52, 0x5f, 0x43, 0x41, 0x4e,
	0x43, 0x45, 0x4c, 0x10, 0x05, 0x12, 0x10, 0x0a, 0x0c, 0x46, 0x49, 0x4c, 0x4c, 0x5f, 0x4f, 0x52,
	0x5f, 0x4b, 0x49, 0x4c, 0x4c, 0x10, 0x06, 0x12, 0x11, 0x0a, 0x0d, 0x47, 0x4f, 0x4f, 0x44, 0x5f,
	0x54, 0x49, 0x4c, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x10, 0x07, 0x2a, 0x58, 0x0a, 0x09, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x19, 0x4e, 0x4f, 0x54, 0x5f, 0x41,
	0x50, 0x50, 0x4c, 0x49, 0x43, 0x41, 0x42, 0x4c, 0x45, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x55, 0x52, 0x43, 0x48, 0x41, 0x53, 0x45, 0x10, 0x01, 0x12,
	0x13, 0x0a, 0x0f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x45,
	0x4c, 0x4c, 0x10, 0x02, 0x2a, 0x93, 0x01, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x4e, 0x4f, 0x54, 0x5f, 0x55, 0x53, 0x45,
	0x44, 0x5f, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10,
	0x00, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x45, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x52, 0x4f,
	0x43, 0x45, 0x53, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x4c, 0x4f, 0x43, 0x4b, 0x45,
	0x44, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x12, 0x1b, 0x0a,
	0x17, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50,
	0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x45, 0x44, 0x10, 0x04, 0x2a, 0x43, 0x0a, 0x0e, 0x43, 0x6c,
	0x65, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x18,
	0x4e, 0x4f, 0x54, 0x5f, 0x55, 0x53, 0x45, 0x44, 0x5f, 0x43, 0x4c, 0x45, 0x41, 0x52, 0x49, 0x4e,
	0x47, 0x5f, 0x42, 0x52, 0x4f, 0x4b, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x4c,
	0x50, 0x41, 0x43, 0x41, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x51, 0x44, 0x10, 0x02, 0x42,
	0x4f, 0x5a, 0x4d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f,
	0x6c, 0x6f, 0x67, 0x65, 0x6e, 0x69, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x2d, 0x66, 0x73, 0x2d, 0x75,
	0x74, 0x69, 0x6c, 0x73, 0x2d, 0x6c, 0x69, 0x62, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x3b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_order_properties_order_properties_proto_rawDescOnce sync.Once
	file_order_properties_order_properties_proto_rawDescData = file_order_properties_order_properties_proto_rawDesc
)

func file_order_properties_order_properties_proto_rawDescGZIP() []byte {
	file_order_properties_order_properties_proto_rawDescOnce.Do(func() {
		file_order_properties_order_properties_proto_rawDescData = protoimpl.X.CompressGZIP(file_order_properties_order_properties_proto_rawDescData)
	})
	return file_order_properties_order_properties_proto_rawDescData
}

var file_order_properties_order_properties_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_order_properties_order_properties_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_order_properties_order_properties_proto_goTypes = []interface{}{
	(Side)(0),                     // 0: orderproperties.Side
	(TimeInForce)(0),              // 1: orderproperties.TimeInForce
	(OrderType)(0),                // 2: orderproperties.OrderType
	(ProcessState)(0),             // 3: orderproperties.ProcessState
	(ClearingBroker)(0),           // 4: orderproperties.ClearingBroker
	(*ProcessInfo)(nil),           // 5: orderproperties.ProcessInfo
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_order_properties_order_properties_proto_depIdxs = []int32{
	3, // 0: orderproperties.ProcessInfo.ProcessState:type_name -> orderproperties.ProcessState
	6, // 1: orderproperties.ProcessInfo.ProcessedAt:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_order_properties_order_properties_proto_init() }
func file_order_properties_order_properties_proto_init() {
	if File_order_properties_order_properties_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_order_properties_order_properties_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_order_properties_order_properties_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_properties_order_properties_proto_goTypes,
		DependencyIndexes: file_order_properties_order_properties_proto_depIdxs,
		EnumInfos:         file_order_properties_order_properties_proto_enumTypes,
		MessageInfos:      file_order_properties_order_properties_proto_msgTypes,
	}.Build()
	File_order_properties_order_properties_proto = out.File
	file_order_properties_order_properties_proto_rawDesc = nil
	file_order_properties_order_properties_proto_goTypes = nil
	file_order_properties_order_properties_proto_depIdxs = nil
}
