// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: order-properties/order-properties.proto

package orderproperties

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Side is order side.
type Side int32

const (
	// SIDE_NOT_APPLICABLE reserves the default value, to protect against unexpected settings.
	Side_SIDE_NOT_APPLICABLE Side = 0
	// SIDE_BUY means that the order is to buy base_denom quantity with the price.
	Side_SIDE_BUY Side = 1
	// SIDE_SELL means that the order is to sell base_denom quantity with the price.
	Side_SIDE_SELL Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_NOT_APPLICABLE",
		1: "SIDE_BUY",
		2: "SIDE_SELL",
	}
	Side_value = map[string]int32{
		"SIDE_NOT_APPLICABLE": 0,
		"SIDE_BUY":            1,
		"SIDE_SELL":           2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_order_properties_order_properties_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_order_properties_order_properties_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_order_properties_order_properties_proto_rawDescGZIP(), []int{0}
}

type TimeInForce int32

const (
	TimeInForce_NOT_USED_TIME_IN_FORCE TimeInForce = 0
	TimeInForce_DAY                    TimeInForce = 1
	TimeInForce_GOOD_TIL_CANCELED      TimeInForce = 2 // GTC
	TimeInForce_AT_THE_OPENING         TimeInForce = 3 // OPG
	TimeInForce_AT_THE_CLOSE           TimeInForce = 4 // CLS
	TimeInForce_IMMEDIATE_OR_CANCEL    TimeInForce = 5 // IOC
	TimeInForce_FILL_OR_KILL           TimeInForce = 6 // FOK
	TimeInForce_GOOD_TIL_TIME          TimeInForce = 7 // GTT
)

// Enum value maps for TimeInForce.
var (
	TimeInForce_name = map[int32]string{
		0: "NOT_USED_TIME_IN_FORCE",
		1: "DAY",
		2: "GOOD_TIL_CANCELED",
		3: "AT_THE_OPENING",
		4: "AT_THE_CLOSE",
		5: "IMMEDIATE_OR_CANCEL",
		6: "FILL_OR_KILL",
		7: "GOOD_TIL_TIME",
	}
	TimeInForce_value = map[string]int32{
		"NOT_USED_TIME_IN_FORCE": 0,
		"DAY":                    1,
		"GOOD_TIL_CANCELED":      2,
		"AT_THE_OPENING":         3,
		"AT_THE_CLOSE":           4,
		"IMMEDIATE_OR_CANCEL":    5,
		"FILL_OR_KILL":           6,
		"GOOD_TIL_TIME":          7,
	}
)

func (x TimeInForce) Enum() *TimeInForce {
	p := new(TimeInForce)
	*p = x
	return p
}

func (x TimeInForce) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeInForce) Descriptor() protoreflect.EnumDescriptor {
	return file_order_properties_order_properties_proto_enumTypes[1].Descriptor()
}

func (TimeInForce) Type() protoreflect.EnumType {
	return &file_order_properties_order_properties_proto_enumTypes[1]
}

func (x TimeInForce) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeInForce.Descriptor instead.
func (TimeInForce) EnumDescriptor() ([]byte, []int) {
	return file_order_properties_order_properties_proto_rawDescGZIP(), []int{1}
}

type OrderType int32

const (
	// Changed not used to NOT_APPLICABLE_ORDER_TYPE to avoid naming conflicts with PURCHASE in the action enum
	OrderType_NOT_APPLICABLE_ORDER_TYPE OrderType = 0
	OrderType_ORDER_TYPE_PURCHASE       OrderType = 1 // Avoid naming conflicts with PURCHASE in the action enum
	OrderType_ORDER_TYPE_SELL           OrderType = 2
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "NOT_APPLICABLE_ORDER_TYPE",
		1: "ORDER_TYPE_PURCHASE",
		2: "ORDER_TYPE_SELL",
	}
	OrderType_value = map[string]int32{
		"NOT_APPLICABLE_ORDER_TYPE": 0,
		"ORDER_TYPE_PURCHASE":       1,
		"ORDER_TYPE_SELL":           2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_order_properties_order_properties_proto_enumTypes[2].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_order_properties_order_properties_proto_enumTypes[2]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_order_properties_order_properties_proto_rawDescGZIP(), []int{2}
}

type ProcessState int32

const (
	ProcessState_NOT_USED_PROCESS_STATE  ProcessState = 0
	ProcessState_PROCESS_STATE_OPEN      ProcessState = 1
	ProcessState_PROCESS_STATE_LOCKED    ProcessState = 2
	ProcessState_PROCESS_STATE_FAILED    ProcessState = 3
	ProcessState_PROCESS_STATE_PROCESSED ProcessState = 4
)

// Enum value maps for ProcessState.
var (
	ProcessState_name = map[int32]string{
		0: "NOT_USED_PROCESS_STATE",
		1: "PROCESS_STATE_OPEN",
		2: "PROCESS_STATE_LOCKED",
		3: "PROCESS_STATE_FAILED",
		4: "PROCESS_STATE_PROCESSED",
	}
	ProcessState_value = map[string]int32{
		"NOT_USED_PROCESS_STATE":  0,
		"PROCESS_STATE_OPEN":      1,
		"PROCESS_STATE_LOCKED":    2,
		"PROCESS_STATE_FAILED":    3,
		"PROCESS_STATE_PROCESSED": 4,
	}
)

func (x ProcessState) Enum() *ProcessState {
	p := new(ProcessState)
	*p = x
	return p
}

func (x ProcessState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessState) Descriptor() protoreflect.EnumDescriptor {
	return file_order_properties_order_properties_proto_enumTypes[3].Descriptor()
}

func (ProcessState) Type() protoreflect.EnumType {
	return &file_order_properties_order_properties_proto_enumTypes[3]
}

func (x ProcessState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessState.Descriptor instead.
func (ProcessState) EnumDescriptor() ([]byte, []int) {
	return file_order_properties_order_properties_proto_rawDescGZIP(), []int{3}
}

type ClearingBroker int32

const (
	ClearingBroker_NOT_USED_CLEARING_BROKER ClearingBroker = 0
	ClearingBroker_ALPACA                   ClearingBroker = 1
	ClearingBroker_RQD                      ClearingBroker = 2
)

// Enum value maps for ClearingBroker.
var (
	ClearingBroker_name = map[int32]string{
		0: "NOT_USED_CLEARING_BROKER",
		1: "ALPACA",
		2: "RQD",
	}
	ClearingBroker_value = map[string]int32{
		"NOT_USED_CLEARING_BROKER": 0,
		"ALPACA":                   1,
		"RQD":                      2,
	}
)

func (x ClearingBroker) Enum() *ClearingBroker {
	p := new(ClearingBroker)
	*p = x
	return p
}

func (x ClearingBroker) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClearingBroker) Descriptor() protoreflect.EnumDescriptor {
	return file_order_properties_order_properties_proto_enumTypes[4].Descriptor()
}

func (ClearingBroker) Type() protoreflect.EnumType {
	return &file_order_properties_order_properties_proto_enumTypes[4]
}

func (x ClearingBroker) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClearingBroker.Descriptor instead.
func (ClearingBroker) EnumDescriptor() ([]byte, []int) {
	return file_order_properties_order_properties_proto_rawDescGZIP(), []int{4}
}

type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessState  ProcessState           `protobuf:"varint,1,opt,name=ProcessState,proto3,enum=orderproperties.ProcessState" json:"ProcessState,omitempty"`
	ProcessedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ProcessedAt,proto3" json:"ProcessedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_order_properties_order_properties_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_properties_order_properties_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_order_properties_order_properties_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessInfo) GetProcessState() ProcessState {
	if x != nil {
		return x.ProcessState
	}
	return ProcessState_NOT_USED_PROCESS_STATE
}

func (x *ProcessInfo) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

var File_order_properties_order_properties_proto protoreflect.FileDescriptor

const file_order_properties_order_properties_proto_rawDesc = "" +
	"\n" +
	"'order-properties/order-properties.proto\x12\x0forderproperties\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x01\n" +
	"\vProcessInfo\x12A\n" +
	"\fProcessState\x18\x01 \x01(\x0e2\x1d.orderproperties.ProcessStateR\fProcessState\x12<\n" +
	"\vProcessedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vProcessedAt*<\n" +
	"\x04Side\x12\x17\n" +
	"\x13SIDE_NOT_APPLICABLE\x10\x00\x12\f\n" +
	"\bSIDE_BUY\x10\x01\x12\r\n" +
	"\tSIDE_SELL\x10\x02*\xad\x01\n" +
	"\vTimeInForce\x12\x1a\n" +
	"\x16NOT_USED_TIME_IN_FORCE\x10\x00\x12\a\n" +
	"\x03DAY\x10\x01\x12\x15\n" +
	"\x11GOOD_TIL_CANCELED\x10\x02\x12\x12\n" +
	"\x0eAT_THE_OPENING\x10\x03\x12\x10\n" +
	"\fAT_THE_CLOSE\x10\x04\x12\x17\n" +
	"\x13IMMEDIATE_OR_CANCEL\x10\x05\x12\x10\n" +
	"\fFILL_OR_KILL\x10\x06\x12\x11\n" +
	"\rGOOD_TIL_TIME\x10\a*X\n" +
	"\tOrderType\x12\x1d\n" +
	"\x19NOT_APPLICABLE_ORDER_TYPE\x10\x00\x12\x17\n" +
	"\x13ORDER_TYPE_PURCHASE\x10\x01\x12\x13\n" +
	"\x0fORDER_TYPE_SELL\x10\x02*\x93\x01\n" +
	"\fProcessState\x12\x1a\n" +
	"\x16NOT_USED_PROCESS_STATE\x10\x00\x12\x16\n" +
	"\x12PROCESS_STATE_OPEN\x10\x01\x12\x18\n" +
	"\x14PROCESS_STATE_LOCKED\x10\x02\x12\x18\n" +
	"\x14PROCESS_STATE_FAILED\x10\x03\x12\x1b\n" +
	"\x17PROCESS_STATE_PROCESSED\x10\x04*C\n" +
	"\x0eClearingBroker\x12\x1c\n" +
	"\x18NOT_USED_CLEARING_BROKER\x10\x00\x12\n" +
	"\n" +
	"\x06ALPACA\x10\x01\x12\a\n" +
	"\x03RQD\x10\x02BOZMgithub.com/sologenic/com-fs-utils-lib/models/order-properties;orderpropertiesb\x06proto3"

var (
	file_order_properties_order_properties_proto_rawDescOnce sync.Once
	file_order_properties_order_properties_proto_rawDescData []byte
)

func file_order_properties_order_properties_proto_rawDescGZIP() []byte {
	file_order_properties_order_properties_proto_rawDescOnce.Do(func() {
		file_order_properties_order_properties_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_properties_order_properties_proto_rawDesc), len(file_order_properties_order_properties_proto_rawDesc)))
	})
	return file_order_properties_order_properties_proto_rawDescData
}

var file_order_properties_order_properties_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_order_properties_order_properties_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_order_properties_order_properties_proto_goTypes = []any{
	(Side)(0),                     // 0: orderproperties.Side
	(TimeInForce)(0),              // 1: orderproperties.TimeInForce
	(OrderType)(0),                // 2: orderproperties.OrderType
	(ProcessState)(0),             // 3: orderproperties.ProcessState
	(ClearingBroker)(0),           // 4: orderproperties.ClearingBroker
	(*ProcessInfo)(nil),           // 5: orderproperties.ProcessInfo
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_order_properties_order_properties_proto_depIdxs = []int32{
	3, // 0: orderproperties.ProcessInfo.ProcessState:type_name -> orderproperties.ProcessState
	6, // 1: orderproperties.ProcessInfo.ProcessedAt:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_order_properties_order_properties_proto_init() }
func file_order_properties_order_properties_proto_init() {
	if File_order_properties_order_properties_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_properties_order_properties_proto_rawDesc), len(file_order_properties_order_properties_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_properties_order_properties_proto_goTypes,
		DependencyIndexes: file_order_properties_order_properties_proto_depIdxs,
		EnumInfos:         file_order_properties_order_properties_proto_enumTypes,
		MessageInfos:      file_order_properties_order_properties_proto_msgTypes,
	}.Build()
	File_order_properties_order_properties_proto = out.File
	file_order_properties_order_properties_proto_goTypes = nil
	file_order_properties_order_properties_proto_depIdxs = nil
}
